
const state = {
  subjects: [], allQuestions: [], currentSubject: null, currentSelectionMeta: null,
  currentGroups: [], selectedGroups: [], selectedMode: null, selectedDirection: null, extraTime: 0, extraTimeAdded: false,
  currentExam: null, favorites: [], wrongQuestions: [], progress: {},
  settings: {}, subjectPreferences: { order: [], pinned: [] }, discoveredRepo: null,
  statsSettings: { lectures: true, years: true, ai: true },
  statsExpand: { subjects: {}, sections: {} },
  toastTimer: null, timerInterval: null, audioUnlocked: false, longPressTimer: null, openSubjectActionId: null,
  dialog: { onConfirm: null, onCancel: null }
};

const STORAGE_KEYS = {
  settings: 'medical-app-settings-v10', progress: 'medical-app-progress-v10', favorites: 'medical-app-favorites-v10',
  wrong: 'medical-app-wrong-v10', examState: 'medical-app-exam-state-v10', subjectPrefs: 'medical-app-subject-prefs-v10',
  statsPrefs: 'medical-app-stats-prefs-v10'
};
const DEFAULT_SETTINGS = { darkMode:false, theme:'default', bgSound:'none', bgSoundEnabled:true, volume:50, feedbackEnabled:true, animations:true };
const IGNORE_ROOT_DIRS = new Set(['.git','.github','node_modules','assets','asset','audio','audios','img','images','css','js','docs','dist','build']);
const BACKGROUND_SOUNDS = { none:{file:''}, cafeteria:{file:'Cafeteria.mp3'}, 'after-exam':{file:'After the exam.mp3'}, beach:{file:'Beach.mp3'}, forest:{file:'Forest.mp3'}, fireplace:{file:'Fireplace.mp3'}, 'rain-thunder':{file:'Rain-thunder.mp3'}, 'rain-window':{file:'Rain-window.mp3'} };
const THEMES = {
  default:{icons:{exams:'📝',wrong:'❌',favorites:'⭐',search:'🔍',statistics:'📊',settings:'⚙️',lectures:'📚',ai:'🤖',years:'📅',results:'🏆',progress:'🎯',location:'📍',success:'✅',error:'❌',review:'🧾',subject:'📘'},texts:{startExam:'🚀 Start Exam',resultsTitle:'Results',statsTitle:'📊 الإحصائيات',settingsTitle:'⚙️ الإعدادات',examSettingsTitle:'⚙️ Exam Settings',examSettingsButton:'⚙️ Exam Settings',trainingLabel:'Training Mode',examLabel:'Real Exam Mode'}},
  desert:{icons:{exams:'🏹',wrong:'🦂',favorites:'🌵',search:'🔎',statistics:'🧭',settings:'🏕️',lectures:'📜',ai:'🔥',years:'📅',results:'👑',progress:'🏹',location:'🧭',success:'🤎',error:'🦂',review:'📜',subject:'🏜️'},texts:{startExam:'🐪 Start Journey',resultsTitle:'Majlis Report',statsTitle:'🧭 إحصائيات الرحلة',settingsTitle:'🏕️ إعدادات الخيمة',examSettingsTitle:'🏕️ Exam Camp Settings',examSettingsButton:'🏕️ Exam Settings',trainingLabel:'Training Camp',examLabel:'Journey Exam'}},
  space:{icons:{exams:'🚀',wrong:'☄️',favorites:'🌟',search:'🔭',statistics:'📡',settings:'🤖',lectures:'🛰️',ai:'👽',years:'🪐',results:'🌌',progress:'🎯',location:'📡',success:'✨',error:'☄️',review:'🧾',subject:'🪐'},texts:{startExam:'🚀 Launch Mission',resultsTitle:'Mission Report',statsTitle:'📡 Mission Analytics',settingsTitle:'🤖 Space Controls',examSettingsTitle:'🤖 Mission Controls',examSettingsButton:'🤖 Mission Settings',trainingLabel:'Training Mission',examLabel:'Space Mission'}},
  pirates:{icons:{exams:'☠️',wrong:'🦈',favorites:'💰',search:'🔎',statistics:'🧭',settings:'⚓',lectures:'🗺️',ai:'🦜',years:'🗓️',results:'👑',progress:'🏴‍☠️',location:'🧭',success:'🪙',error:'🦈',review:'📜',subject:'⚓'},texts:{startExam:'☠️ Start Voyage',resultsTitle:'Treasure Report',statsTitle:'🧭 Voyage Progress',settingsTitle:'⚓ Captain Settings',examSettingsTitle:'⚓ Voyage Settings',examSettingsButton:'⚓ Voyage Settings',trainingLabel:'Deck Training',examLabel:'Treasure Voyage'}},
  castle:{icons:{exams:'⚔️',wrong:'🐉',favorites:'👑',search:'🔎',statistics:'🛡️',settings:'🏰',lectures:'📜',ai:'🕯️',years:'📅',results:'👑',progress:'🏹',location:'🛡️',success:'🛡️',error:'🐉',review:'📜',subject:'🏰'},texts:{startExam:'⚔️ Begin Quest',resultsTitle:'Kingdom Report',statsTitle:'🛡️ Quest Progress',settingsTitle:'🏰 Castle Settings',examSettingsTitle:'🏰 Quest Settings',examSettingsButton:'🏰 Quest Settings',trainingLabel:'Knight Training',examLabel:'Kingdom Trial'}},
  lab:{icons:{exams:'🧪',wrong:'☣️',favorites:'🧬',search:'🔬',statistics:'📈',settings:'⚗️',lectures:'🔬',ai:'🧠',years:'📅',results:'🏅',progress:'🧫',location:'📍',success:'🧫',error:'☣️',review:'📋',subject:'⚗️'},texts:{startExam:'🧪 Start Experiment',resultsTitle:'Research Report',statsTitle:'📈 Experiment Progress',settingsTitle:'⚗️ Lab Settings',examSettingsTitle:'⚗️ Experiment Settings',examSettingsButton:'⚗️ Experiment Settings',trainingLabel:'Trial Run',examLabel:'Main Experiment'}}
};

function el(id){ return document.getElementById(id); }
function theme(){ return THEMES[state.settings.theme] || THEMES.default; }
function showScreen(id){ document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active')); const t=el(id); if(t) t.classList.add('active'); }
function slugify(text){ return String(text||'').toLowerCase().replace(/[^a-z0-9\u0600-\u06FF]+/g,'-').replace(/^-+|-+$/g,'') || 'item'; }
function hashString(input){ let h=0; const s=String(input||''); for(let i=0;i<s.length;i++){ h=((h<<5)-h)+s.charCodeAt(i); h|=0; } return Math.abs(h).toString(36); }
function escapeHtml(v){ return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;'); }
function escapeJsString(v){ return String(v==null?'':v).replace(/\\/g,'\\\\').replace(/'/g,"\\'"); }
function shortenText(t,m){ const s=String(t||''); return s.length>m ? s.slice(0,m).trim()+'...' : s; }
function clampNum(v,min,max,fallback){ return Number.isNaN(v)?fallback:Math.min(max,Math.max(min,v)); }
function shuffleArray(arr){ const a=arr.slice(); for(let i=a.length-1;i>0;i--){ const j=Math.floor(Math.random()*(i+1)); [a[i],a[j]]=[a[j],a[i]]; } return a; }
function normalizeComparisonText(text){ return String(text||'').toLowerCase().replace(/^[a-e][\)\.\-]\s*/i,'').replace(/\s+/g,' ').trim(); }
function isPageLine(line){ return /^P\s*\(?\s*\d+\s*\)?$/i.test(line) || /^Page\s*\d+$/i.test(line); }
function isBatchLine(line){ return /^[A-Za-z][A-Za-z0-9\s&()'\/]+-\s*\d+$/i.test(line) || /^\d+(st|nd|rd|th)\s+Year/i.test(line); }
function looksLikeMetadataTail(line){ return /^[A-Za-z].{0,60}$/.test(line) && /\d/.test(line) && !/[?.!]$/.test(line); }
function isMetadataLine(line){ return isPageLine(line) || isBatchLine(line) || looksLikeMetadataTail(line); }
function resolveCorrectIndex(options, correctAnswer){ if(!Array.isArray(options)||!options.length) return -1; const m=String(correctAnswer||'').match(/^([A-E])/i); if(m){ const ix=m[1].toUpperCase().charCodeAt(0)-65; if(ix>=0&&ix<options.length) return ix; } const ans=normalizeComparisonText(correctAnswer); for(let i=0;i<options.length;i++){ const opt=normalizeComparisonText(options[i]); if(opt && (opt.includes(ans)||ans.includes(opt))) return i; } return -1; }
function getCorrectIndex(q){ if(typeof q.correctIndex==='number' && q.correctIndex>=0) return q.correctIndex; q.correctIndex=resolveCorrectIndex(q.options||[], q.correctAnswer||''); return q.correctIndex; }
function isAnswerCorrect(q, idx){ return getCorrectIndex(q)===idx; }

function saveSettings(){ localStorage.setItem(STORAGE_KEYS.settings, JSON.stringify(state.settings)); }
function loadSettings(){ try{ state.settings=Object.assign({}, DEFAULT_SETTINGS, JSON.parse(localStorage.getItem(STORAGE_KEYS.settings))||{}); }catch{ state.settings=Object.assign({}, DEFAULT_SETTINGS); } }
function saveFavorites(){ localStorage.setItem(STORAGE_KEYS.favorites, JSON.stringify(state.favorites)); }
function loadFavorites(){ try{ state.favorites=JSON.parse(localStorage.getItem(STORAGE_KEYS.favorites))||[]; }catch{ state.favorites=[]; } }
function saveWrongQuestions(){ localStorage.setItem(STORAGE_KEYS.wrong, JSON.stringify(state.wrongQuestions)); }
function loadWrongQuestions(){ try{ state.wrongQuestions=JSON.parse(localStorage.getItem(STORAGE_KEYS.wrong))||[]; }catch{ state.wrongQuestions=[]; } }
function saveProgressStore(){ localStorage.setItem(STORAGE_KEYS.progress, JSON.stringify(state.progress)); }
function loadProgress(){ try{ state.progress=JSON.parse(localStorage.getItem(STORAGE_KEYS.progress))||{}; }catch{ state.progress={}; } }
function saveExamState(){ if(state.currentExam) localStorage.setItem(STORAGE_KEYS.examState, JSON.stringify(state.currentExam)); }
function clearExamState(){ localStorage.removeItem(STORAGE_KEYS.examState); }
function saveSubjectPreferences(){ localStorage.setItem(STORAGE_KEYS.subjectPrefs, JSON.stringify(state.subjectPreferences)); }
function loadSubjectPreferences(){ try{ state.subjectPreferences=Object.assign({order:[],pinned:[]}, JSON.parse(localStorage.getItem(STORAGE_KEYS.subjectPrefs))||{}); }catch{ state.subjectPreferences={order:[],pinned:[]}; } }
function saveStatsSettings(){ localStorage.setItem(STORAGE_KEYS.statsPrefs, JSON.stringify(state.statsSettings)); }
function loadStatsSettings(){ try{ state.statsSettings=Object.assign({lectures:true,years:true,ai:true}, JSON.parse(localStorage.getItem(STORAGE_KEYS.statsPrefs))||{}); }catch{ state.statsSettings={lectures:true,years:true,ai:true}; } }
function addProgressId(key, qid){ if(!state.progress[key]) state.progress[key]={questionIds:[]}; if(!state.progress[key].questionIds.includes(qid)) state.progress[key].questionIds.push(qid); }

function normalizeSubjectPreferences(){ const ids=state.subjects.map(s=>s.id); state.subjectPreferences.order=(state.subjectPreferences.order||[]).filter(id=>ids.includes(id)); state.subjectPreferences.pinned=(state.subjectPreferences.pinned||[]).filter(id=>ids.includes(id)); ids.forEach(id=>{ if(!state.subjectPreferences.order.includes(id)) state.subjectPreferences.order.push(id); }); saveSubjectPreferences(); }
function sortSubjects(list){ const orderMap=new Map(); (state.subjectPreferences.order||[]).forEach((id,idx)=>orderMap.set(id,idx)); const pinned=new Set(state.subjectPreferences.pinned||[]); return list.slice().sort((a,b)=>{ const ap=pinned.has(a.id)?1:0, bp=pinned.has(b.id)?1:0; if(ap!==bp) return bp-ap; const ao=orderMap.has(a.id)?orderMap.get(a.id):Number.MAX_SAFE_INTEGER; const bo=orderMap.has(b.id)?orderMap.get(b.id):Number.MAX_SAFE_INTEGER; if(ao!==bo) return ao-bo; return a.name.localeCompare(b.name,'en',{sensitivity:'base'}); }); }

function applyThemeUI(){ const t=theme(); el('nav-icon-exams').textContent=t.icons.exams; el('nav-icon-wrong').textContent=t.icons.wrong; el('nav-icon-favorites').textContent=t.icons.favorites; el('nav-icon-search').textContent=t.icons.search; el('nav-icon-statistics').textContent=t.icons.statistics; el('nav-icon-settings').textContent=t.icons.settings; el('statistics-title').textContent=t.texts.statsTitle; el('settings-title').textContent=t.texts.settingsTitle; el('exam-settings-title').textContent=t.texts.examSettingsTitle; el('btn-exam-settings').textContent=t.texts.examSettingsButton; el('btn-start-exam').textContent=t.texts.startExam; const a=document.querySelector('#btn-training-mode .mode-label'); const b=document.querySelector('#btn-exam-mode .mode-label'); if(a) a.textContent=t.texts.trainingLabel; if(b) b.textContent=t.texts.examLabel; }
function syncSettingsControls(){ const entries=[['dark-mode-toggle','checked',!!state.settings.darkMode],['theme-selector','value',state.settings.theme],['exam-theme-selector','value',state.settings.theme],['sound-selector','value',state.settings.bgSound],['exam-sound-selector','value',state.settings.bgSound],['bg-sound-enabled-toggle','checked',state.settings.bgSoundEnabled!==false],['exam-bg-sound-enabled-toggle','checked',state.settings.bgSoundEnabled!==false],['volume-control','value',state.settings.volume],['exam-volume-control','value',state.settings.volume],['feedback-toggle','checked',state.settings.feedbackEnabled!==false],['exam-feedback-toggle','checked',state.settings.feedbackEnabled!==false],['animations-toggle','checked',state.settings.animations!==false],['stats-show-lectures','checked',state.statsSettings.lectures!==false],['stats-show-years','checked',state.statsSettings.years!==false],['stats-show-ai','checked',state.statsSettings.ai!==false]]; entries.forEach(([id,prop,val])=>{ const x=el(id); if(x) x[prop]=val; }); }
async function resolveAssetPath(candidates){ for(const item of candidates.filter(Boolean)){ try{ const u=encodeURI(item); const r=await fetch(u,{method:'HEAD'}); if(r.ok) return u; }catch(e){} } return encodeURI(candidates.find(Boolean)||''); }
async function applyBackgroundSound(){ const audio=el('bg-audio'); if(!audio) return; audio.volume=(state.settings.volume||50)/100; const key=state.settings.bgSound||'none'; const sound=BACKGROUND_SOUNDS[key]||BACKGROUND_SOUNDS.none; if(!state.settings.bgSoundEnabled || key==='none' || !sound.file){ audio.pause(); return; } const src=await resolveAssetPath([sound.file,'audio/'+sound.file,'assets/audio/'+sound.file]); if(audio.dataset.currentSrc!==src){ audio.src=src; audio.dataset.currentSrc=src; audio.load(); } if(state.audioUnlocked) audio.play().catch(()=>{}); }
function applyEffectAudioVolumes(){ ['right-audio','wrong-audio','celebrate-audio'].forEach(id=>{ const a=el(id); if(a) a.volume=(state.settings.volume||50)/100; }); }
async function prepareStaticEffectAudio(){ el('right-audio').src=await resolveAssetPath(['right.mp3','audio/right.mp3','assets/audio/right.mp3']); el('wrong-audio').src=await resolveAssetPath(['wrong.mp3','audio/wrong.mp3','assets/audio/wrong.mp3']); el('celebrate-audio').src=await resolveAssetPath(['celebrate.mp3','audio/celebrate.mp3','assets/audio/celebrate.mp3']); applyEffectAudioVolumes(); }
function primeAudioUnlock(){ function unlock(){ if(state.audioUnlocked) return; state.audioUnlocked=true; applyBackgroundSound(); document.removeEventListener('click',unlock); document.removeEventListener('touchstart',unlock); document.removeEventListener('keydown',unlock); } document.addEventListener('click',unlock,{once:true}); document.addEventListener('touchstart',unlock,{once:true}); document.addEventListener('keydown',unlock,{once:true}); }
function playEffectSound(kind){ if(!state.currentExam || state.currentExam.mode!=='training' || state.settings.feedbackEnabled===false) return; const a=el(kind==='right'?'right-audio':'wrong-audio'); if(!a||!a.src) return; try{ a.currentTime=0; a.play().catch(()=>{}); }catch(e){} }
function playCelebrateSound(){ const a=el('celebrate-audio'); if(!a||!a.src) return; try{ a.currentTime=0; a.play().catch(()=>{}); }catch(e){} }

function applySettings(){ state.settings=Object.assign({},DEFAULT_SETTINGS,state.settings||{}); document.documentElement.setAttribute('data-dark', String(!!state.settings.darkMode)); document.documentElement.setAttribute('data-theme', state.settings.theme||'default'); document.documentElement.setAttribute('data-animations', String(state.settings.animations!==false)); syncSettingsControls(); applyThemeUI(); applyBackgroundSound(); applyEffectAudioVolumes(); }
function changeTheme(name){ state.settings.theme = THEMES[name] ? name : 'default'; saveSettings(); applySettings(); renderSubjects(); if(state.currentSubject && el('subject-sections-screen').classList.contains('active')) openSubject(state.currentSubject.id); if(state.currentExam && el('exam-screen').classList.contains('active')) renderExam(); updateStatisticsIfOpen(); }
function changeSound(name){ state.settings.bgSound = BACKGROUND_SOUNDS[name] ? name : 'none'; saveSettings(); applySettings(); }
function changeVolume(v){ state.settings.volume=clampNum(parseInt(v,10),0,100,50); saveSettings(); applySettings(); }
function toggleDarkMode(){ state.settings.darkMode=!!el('dark-mode-toggle').checked; saveSettings(); applySettings(); }
function toggleBackgroundSoundEnabled(){ const src=document.activeElement && (document.activeElement.id==='exam-bg-sound-enabled-toggle' || document.activeElement.id==='bg-sound-enabled-toggle') ? document.activeElement : el('bg-sound-enabled-toggle'); state.settings.bgSoundEnabled=!!src.checked; saveSettings(); applySettings(); }
function toggleFeedbackSounds(){ const src=document.activeElement && (document.activeElement.id==='exam-feedback-toggle' || document.activeElement.id==='feedback-toggle') ? document.activeElement : el('feedback-toggle'); state.settings.feedbackEnabled=!!src.checked; saveSettings(); applySettings(); }
function toggleAnimations(){ state.settings.animations=!!el('animations-toggle').checked; saveSettings(); applySettings(); }
function toggleSettings(){ el('settings-panel').classList.toggle('visible'); }
function toggleExamSettings(show){ el('exam-settings-modal').classList.toggle('hidden', !show); if(show) syncSettingsControls(); }
function toggleStatisticsSettings(show){ el('stats-settings-modal').classList.toggle('hidden', !show); if(show) syncSettingsControls(); }
function updateStatisticsType(kind, checked){ state.statsSettings[kind]=!!checked; saveStatsSettings(); syncSettingsControls(); updateStatisticsIfOpen(); }

function showToast(message, kind='info'){ const toast=el('toast'); clearTimeout(state.toastTimer); const prefix=(theme().icons[kind] || theme().icons.statistics || 'ℹ️'); toast.textContent=prefix+' '+message; toast.classList.remove('hidden'); toast.classList.add('visible'); state.toastTimer=setTimeout(()=>{ toast.classList.remove('visible'); toast.classList.add('hidden'); },2600); }
function showDialog({title='تنبيه', message='', showCancel=false, confirmText='موافق', cancelText='إلغاء', onConfirm=null, onCancel=null}){ el('dialog-title').textContent=title; el('dialog-body').innerHTML=message; const cancel=el('dialog-cancel'); const confirm=el('dialog-confirm'); cancel.classList.toggle('hidden', !showCancel); cancel.textContent=cancelText; confirm.textContent=confirmText; state.dialog.onConfirm=onConfirm; state.dialog.onCancel=onCancel; el('dialog-overlay').classList.remove('hidden'); }
function hideDialog(){ el('dialog-overlay').classList.add('hidden'); state.dialog.onConfirm=null; state.dialog.onCancel=null; }
function dialogConfirmAction(){ const fn=state.dialog.onConfirm; hideDialog(); if(typeof fn==='function') fn(); }
function dialogCancelAction(){ const fn=state.dialog.onCancel; hideDialog(); if(typeof fn==='function') fn(); }
function askConfirm(message,onConfirm,onCancel){ showDialog({title:'تأكيد',message,showCancel:true,confirmText:'تأكيد',cancelText:'إلغاء',onConfirm,onCancel}); }

async function discoverRepository(){ const hostname=window.location.hostname; if(!hostname.endsWith('github.io')) return null; const owner=hostname.split('.')[0]; const pathParts=window.location.pathname.split('/').filter(Boolean); const repo=pathParts.length>0 ? pathParts[0] : owner+'.github.io'; const resp=await fetch('https://api.github.com/repos/'+owner+'/'+repo); if(!resp.ok) throw new Error('Unable to read repository metadata.'); const data=await resp.json(); return {owner,repo,branch:data.default_branch||'main'}; }
async function listRepoDirectory(path){ const clean=path ? encodeURIComponent(path).replace(/%2F/g,'/') : ''; const url='https://api.github.com/repos/'+state.discoveredRepo.owner+'/'+state.discoveredRepo.repo+'/contents/'+clean+'?ref='+encodeURIComponent(state.discoveredRepo.branch); const resp=await fetch(url,{headers:{Accept:'application/vnd.github+json'}}); if(!resp.ok) throw new Error('Unable to read directory: '+(path||'root')); const data=await resp.json(); return Array.isArray(data)?data:[]; }
async function fetchQuestionFile(fileItem){ if(fileItem.download_url){ const r=await fetch(fileItem.download_url); if(r.ok) return await r.text(); } const url='https://raw.githubusercontent.com/'+state.discoveredRepo.owner+'/'+state.discoveredRepo.repo+'/'+state.discoveredRepo.branch+'/'+fileItem.path; const r=await fetch(url); if(!r.ok) throw new Error('Unable to fetch file: '+fileItem.path); return await r.text(); }
function parseQuestionFile(raw, meta){ const text=String(raw||'').replace(/^\uFEFF/,'').replace(/\r\n/g,'\n').replace(/\r/g,'\n').replace(/\t/g,'    ').replace(/\/\/\/\/\//g,'\n').trim(); if(!text) return []; let blocks=text.split(/(?:^|\n)\s*###\s*(?=\n|$)/g).map(x=>x.trim()).filter(Boolean); if(blocks.length<=1){ const paragraphs=text.split(/\n{2,}/).map(x=>x.trim()).filter(Boolean); if(paragraphs.length<=1) blocks=[text]; else { blocks=[]; let current=[]; let hasCorrect=false; for(let i=0;i<paragraphs.length;i++){ const p=paragraphs[i]; const first=(p.split('\n').find(l=>l.trim())||'').trim(); const looksNew=current.length>0 && hasCorrect && !/^(Correct\s*Answer|Explanation)\s*:/i.test(first) && !/^[A-E][\)\.\-]/.test(first) && !isPageLine(first); if(looksNew){ blocks.push(current.join('\n\n').trim()); current=[]; hasCorrect=false; } current.push(p); if(/^\s*Correct\s*Answer\s*:/im.test(p)) hasCorrect=true; if(i===paragraphs.length-1 && current.length) blocks.push(current.join('\n\n').trim()); } } }
  const questions=[]; let fallback=meta.startCounter||1;
  for(let blockIndex=0; blockIndex<blocks.length; blockIndex++){
    const lines=blocks[blockIndex].split('\n').map(l=>l.trim()).filter(Boolean); if(!lines.length || !lines.some(l=>/^Correct\s*Answer\s*:/i.test(l))) continue; let questionNumber=''; let questionText=''; let options=[]; let correctAnswer=''; let explanation=''; let batchName=''; let pageNumber=''; let startIndex=0; const head=(lines[0]||'').match(/^Question\s*(\d+)\s*[:\-.]?\s*(.*)$/i); if(head){ questionNumber=head[1]||''; if(head[2]) lines[0]=head[2].trim(); else startIndex=1; } const ansIdx=lines.findIndex(l=>/^Correct\s*Answer\s*:/i.test(l)); if(ansIdx===-1) continue; const before=lines.slice(startIndex, ansIdx); const firstOpt=before.findIndex(l=>/^[A-E][\)\.\-]\s*/i.test(l)); if(firstOpt===-1) continue; questionText=before.slice(0,firstOpt).join(' ').trim() || ('Question '+fallback); options=before.slice(firstOpt).filter(l=>/^[A-E][\)\.\-]\s*/i.test(l)); correctAnswer=lines[ansIdx].replace(/^Correct\s*Answer\s*:\s*/i,'').trim(); let i=ansIdx+1; if(i<lines.length && /^Explanation\s*:/i.test(lines[i])){ const exp=[]; const first=lines[i].replace(/^Explanation\s*:\s*/i,'').trim(); if(first) exp.push(first); i++; while(i<lines.length && !isMetadataLine(lines[i])){ exp.push(lines[i]); i++; } explanation=exp.join(' ').trim(); } while(i<lines.length){ const line=lines[i]; if(isPageLine(line)) pageNumber=line; else if(!batchName && isBatchLine(line)) batchName=line; else if(!batchName && looksLikeMetadataTail(line)) batchName=line; else if(!explanation && !/^Explanation\s*:/i.test(line)) explanation=[explanation,line].filter(Boolean).join(' ').trim(); i++; } if(!questionNumber) questionNumber=String(fallback); const id=[slugify(meta.subjectName),slugify(meta.sourceType),slugify(meta.lectureName),slugify(questionNumber),hashString(questionText).slice(0,10)].join('__'); questions.push({id,number:questionNumber,text:questionText,options,correctAnswer,correctIndex:resolveCorrectIndex(options,correctAnswer),explanation,batchName,pageNumber,subjectName:meta.subjectName,lectureName:meta.lectureName,groupName:meta.lectureName,sourceType:meta.sourceType,sourcePath:meta.sourcePath}); fallback++; }
  return questions;
}
async function buildLectureGroupFromFile(fileItem, subjectName, sourceType, startCounter){ const text=await fetchQuestionFile(fileItem); const lectureName=fileItem.name.replace(/\.txt$/i,''); const questions=parseQuestionFile(text,{subjectName,lectureName,sourceType,sourcePath:fileItem.path,startCounter}); if(!questions.length) return null; return {id:slugify(subjectName)+'__'+sourceType+'__'+slugify(lectureName),name:lectureName,type:sourceType,subjectName,path:fileItem.path,questions}; }
async function scanSubjectFolder(dirItem){ const items=await listRepoDirectory(dirItem.path); const lectureFiles=items.filter(it=>it.type==='file' && it.name.toLowerCase().endsWith('.txt')).sort((a,b)=>a.name.localeCompare(b.name)); const aiFolder=items.find(it=>it.type==='dir' && it.name.toLowerCase()==='ai'); let aiFiles=[]; if(aiFolder){ const aiItems=await listRepoDirectory(aiFolder.path); aiFiles=aiItems.filter(it=>it.type==='file' && it.name.toLowerCase().endsWith('.txt')).sort((a,b)=>a.name.localeCompare(b.name)); }
  if(lectureFiles.length===0 && aiFiles.length===0 && !aiFolder){ return {id:slugify(dirItem.name),name:dirItem.name,lectures:[],ai:[],years:[],allQuestions:[],totalQuestions:0,totalLectures:0,hasAiFolder:false}; }
  const lectures=[]; const ai=[]; let counter=1; for(const f of lectureFiles){ const g=await buildLectureGroupFromFile(f,dirItem.name,'lecture',counter); if(g){ counter+=g.questions.length; lectures.push(g);} } for(const f of aiFiles){ const g=await buildLectureGroupFromFile(f,dirItem.name,'ai',counter); if(g){ counter+=g.questions.length; ai.push(g);} } const all=lectures.flatMap(g=>g.questions).concat(ai.flatMap(g=>g.questions)); const yearsMap=new Map(); all.forEach(q=>{ const batch=String(q.batchName||'').trim(); if(!batch) return; if(!yearsMap.has(batch)) yearsMap.set(batch,[]); yearsMap.get(batch).push(Object.assign({},q,{sourceType:'year',originalSourceType:q.sourceType})); }); const years=Array.from(yearsMap.entries()).sort((a,b)=>a[0].localeCompare(b[0],'en',{sensitivity:'base'})).map(([name,questions])=>({id:slugify(dirItem.name)+'__year__'+slugify(name),name,type:'year',subjectName:dirItem.name,questions})); return {id:slugify(dirItem.name),name:dirItem.name,lectures,ai,years,allQuestions:all,totalQuestions:all.length,totalLectures:lectures.length+ai.length,hasAiFolder:!!aiFolder}; }
async function loadData(){ state.subjects=[]; state.allQuestions=[]; state.discoveredRepo=await discoverRepository(); if(!state.discoveredRepo) { renderSubjects(); return; } const root=await listRepoDirectory(''); const subjectDirs=root.filter(item=>item.type==='dir' && !IGNORE_ROOT_DIRS.has(item.name.toLowerCase())); const scanned=[]; for(const dir of subjectDirs){ const s=await scanSubjectFolder(dir); if(s) scanned.push(s); } state.subjects=sortSubjects(scanned); normalizeSubjectPreferences(); state.allQuestions=state.subjects.flatMap(s=>s.allQuestions); populateSearchFilter(); renderSubjects(); updateStatisticsIfOpen(); }

function renderSubjects(){ const container=el('subjects-list'); const empty=el('subjects-empty'); if(!container||!empty) return; state.subjects=sortSubjects(state.subjects); const searchTerm=String(el('subjects-search')?el('subjects-search').value:'').trim().toLowerCase(); const t=theme(); const pinnedSet=new Set(state.subjectPreferences.pinned||[]); const visible=state.subjects.filter(s=>s.name.toLowerCase().includes(searchTerm)); if(!state.subjects.length){ empty.classList.remove('hidden'); container.innerHTML=''; return; } empty.classList.add('hidden'); container.innerHTML=visible.map(subject=>{ const pinned=pinnedSet.has(subject.id); return `<div class="subject-card${state.openSubjectActionId===subject.id?' actions-open':''}" data-subject-id="${subject.id}" onclick="handleSubjectOpen('${subject.id}',event)" onmousedown="startSubjectLongPress('${subject.id}')" ontouchstart="startSubjectLongPress('${subject.id}')" onmouseup="cancelSubjectLongPress()" onmouseleave="cancelSubjectLongPress()" ontouchend="cancelSubjectLongPress()" ontouchcancel="cancelSubjectLongPress()">${pinned?'<span class="subject-pin-badge">📌 مثبت</span>':''}<div class="subject-card-top"><div class="subject-icon-box">${t.icons.subject}</div><div class="subject-title-wrap"><div class="subject-badge-text">${escapeHtml(subject.name)}</div><div class="subject-subtitle">اضغط مطولاً للترتيب والتثبيت</div></div></div><div class="subject-meta"><div><span>${t.icons.lectures} Lectures</span><strong>${subject.totalLectures}</strong></div><div><span>${t.icons.progress} Questions</span><strong>${subject.totalQuestions}</strong></div><div><span>${t.icons.years} Years</span><strong>${subject.years.length}</strong></div></div><div class="subject-actions" onclick="event.stopPropagation()"><button class="subject-action-btn" onclick="moveSubject('${subject.id}','up')">⬆️ أعلى</button><button class="subject-action-btn" onclick="moveSubject('${subject.id}','down')">⬇️ أسفل</button><button class="subject-action-btn" onclick="togglePinSubject('${subject.id}')">${pinned?'📍 إلغاء التثبيت':'📌 تثبيت بالأعلى'}</button></div></div>`; }).join(''); if(!visible.length) container.innerHTML='<div class="empty-state"><div class="empty-icon">🔎</div><p>لا توجد مواد مطابقة للبحث.</p></div>'; }
function filterSubjects(){ renderSubjects(); }
function openExams(){ renderSubjects(); showScreen('subjects-screen'); }
function moveSubject(subjectId,direction){ normalizeSubjectPreferences(); const arr=state.subjectPreferences.order.slice(); const idx=arr.indexOf(subjectId); if(idx===-1) return; const target=direction==='up'?idx-1:idx+1; if(target<0||target>=arr.length) return; [arr[idx],arr[target]]=[arr[target],arr[idx]]; state.subjectPreferences.order=arr; saveSubjectPreferences(); state.subjects=sortSubjects(state.subjects); renderSubjects(); openSubjectActions(subjectId); updateStatisticsIfOpen(); }
function togglePinSubject(subjectId){ normalizeSubjectPreferences(); const pinned=new Set(state.subjectPreferences.pinned||[]); if(pinned.has(subjectId)) pinned.delete(subjectId); else pinned.add(subjectId); state.subjectPreferences.pinned=Array.from(pinned); saveSubjectPreferences(); state.subjects=sortSubjects(state.subjects); renderSubjects(); openSubjectActions(subjectId); updateStatisticsIfOpen(); }
function openSubjectActions(subjectId){ state.openSubjectActionId=subjectId; document.querySelectorAll('.subject-card').forEach(card=>card.classList.toggle('actions-open', card.getAttribute('data-subject-id')===subjectId)); }
function closeSubjectActions(){ state.openSubjectActionId=null; document.querySelectorAll('.subject-card').forEach(card=>card.classList.remove('actions-open')); }
function startSubjectLongPress(subjectId){ clearTimeout(state.longPressTimer); state.longPressTimer=setTimeout(()=>openSubjectActions(subjectId),420); }
function cancelSubjectLongPress(){ clearTimeout(state.longPressTimer); state.longPressTimer=null; }
function handleSubjectOpen(subjectId,event){ if(event && event.target && event.target.closest('.subject-action-btn')) return; if(state.openSubjectActionId===subjectId) return; openSubject(subjectId); }
function openSubject(subjectId){ state.currentSubject=state.subjects.find(s=>s.id===subjectId)||null; if(!state.currentSubject){ showToast('المادة غير موجودة.','error'); return; } const t=theme(); el('subject-sections-title').textContent=state.currentSubject.name; el('subject-sections-summary').innerHTML=`<div class="subject-summary-grid"><div><span>${t.icons.lectures} المحاضرات</span><strong>${state.currentSubject.lectures.length}</strong></div><div><span>${t.icons.ai} AI</span><strong>${state.currentSubject.ai.length}</strong></div><div><span>${t.icons.years} Years</span><strong>${state.currentSubject.years.length}</strong></div><div><span>${t.icons.progress} إجمالي الأسئلة</span><strong>${state.currentSubject.totalQuestions}</strong></div></div>`; const cards=[]; cards.push(buildCategoryCard('ai','AI '+state.currentSubject.name,'AI',state.currentSubject.ai.length,countQuestions(state.currentSubject.ai),state.currentSubject.hasAiFolder||state.currentSubject.ai.length>0)); cards.push(buildCategoryCard('lectures',state.currentSubject.name+' Lectures','Lectures',state.currentSubject.lectures.length,countQuestions(state.currentSubject.lectures),true)); if(state.currentSubject.years.length>0) cards.push(buildCategoryCard('years',state.currentSubject.name+' Years','Years',state.currentSubject.years.length,countQuestions(state.currentSubject.years),true)); el('subject-categories').innerHTML=cards.join('') || '<div class="empty-state"><div class="empty-icon">📭</div><p>لا توجد ملفات TXT بعد داخل هذه المادة.</p></div>'; showScreen('subject-sections-screen'); }
function countQuestions(groups){ return groups.reduce((sum,g)=>sum+g.questions.length,0); }
function buildCategoryCard(type,title,badgeText,itemLabelCount,totalQuestions,enabled){ if(!enabled) return `<div class="category-card" style="opacity:.66;cursor:default;"><span class="category-badge">${badgeText}</span><h4>${escapeHtml(title)}</h4><div class="category-meta"><div><span>المحاضرات</span><strong>0</strong></div><div><span>الأسئلة</span><strong>0</strong></div></div></div>`; return `<button class="category-card" onclick="openSubjectCategory('${type}')"><span class="category-badge">${badgeText}</span><h4>${escapeHtml(title)}</h4><div class="category-meta"><div><span>المحاضرات</span><strong>${itemLabelCount}</strong></div><div><span>الأسئلة</span><strong>${totalQuestions}</strong></div></div></button>`; }
function openSubjectCategory(type){ if(!state.currentSubject) return; let groups=[], title=state.currentSubject.name, placeholder='ابحث...'; if(type==='ai'){ groups=state.currentSubject.ai; title='AI '+state.currentSubject.name; placeholder='ابحث عن ملف AI...'; } else if(type==='lectures'){ groups=state.currentSubject.lectures; title=state.currentSubject.name+' Lectures'; placeholder='ابحث عن اسم المحاضرة...'; } else { groups=state.currentSubject.years; title=state.currentSubject.name+' Years'; placeholder='ابحث عن الدفعة...'; } showSelectionScreen(groups,title,{backContext:'subject', searchable:true, searchPlaceholder:placeholder, sectionType:type}); }
function backFromSelection(){ if(state.currentSelectionMeta && state.currentSelectionMeta.backContext==='subject' && state.currentSubject) openSubject(state.currentSubject.id); else goHome(); }

function showSelectionScreen(groups,title,meta){ state.selectedGroups=[]; state.currentGroups=groups.slice(); state.selectedMode=null; state.selectedDirection=null; state.extraTime=0; state.extraTimeAdded=false; state.currentSelectionMeta=meta||{}; showScreen('selection-screen'); el('selection-title').textContent=title; const searchContainer=el('selection-search-container'); const searchInput=el('selection-search'); if(meta&&meta.searchable){ searchContainer.classList.remove('hidden'); searchInput.value=''; searchInput.placeholder=meta.searchPlaceholder||'ابحث...'; } else { searchContainer.classList.add('hidden'); searchInput.value=''; } const list=el('selection-list'); const t=theme(); list.innerHTML=''; groups.forEach((group,idx)=>{ const icon=group.type==='ai'?t.icons.ai:(group.type==='year'?t.icons.years:t.icons.lectures); const item=document.createElement('div'); item.className='selection-item'; item.setAttribute('data-group-name',(group.name+' '+(group.subjectName||'')).toLowerCase()); item.innerHTML=`<input type="checkbox" id="group-${idx}" onchange="toggleGroupSelection(${idx})"><label for="group-${idx}" style="width:100%; cursor:pointer;"><strong>${icon} ${escapeHtml(group.name)}</strong><br><small style="color:var(--text-muted)">${group.questions.length} questions</small></label>`; item.addEventListener('click',function(event){ if(event.target.closest('input')||event.target.closest('label')) return; const cb=item.querySelector('input'); cb.checked=!cb.checked; toggleGroupSelection(idx); }); list.appendChild(item); }); el('selection-footer').classList.add('hidden'); el('direction-selection').classList.add('hidden'); el('timer-options').classList.add('hidden'); el('start-section').classList.add('hidden'); document.querySelectorAll('.btn-mode').forEach(btn=>btn.classList.remove('active')); document.querySelectorAll('.btn-direction').forEach(btn=>btn.classList.remove('active')); }
function filterSelectionList(){ const term=String(el('selection-search').value||'').toLowerCase().trim(); document.querySelectorAll('#selection-list .selection-item').forEach(item=>{ const name=item.getAttribute('data-group-name')||''; item.style.display=name.includes(term)?'':'none'; }); }
function toggleGroupSelection(idx){ const existing=state.selectedGroups.indexOf(idx); if(existing>-1) state.selectedGroups.splice(existing,1); else state.selectedGroups.push(idx); document.querySelectorAll('#selection-list .selection-item').forEach((item,itemIdx)=>item.classList.toggle('selected', state.selectedGroups.includes(itemIdx))); updateSelectionFooter(); }
function updateSelectionFooter(){ const footer=el('selection-footer'); const totalQuestions=state.selectedGroups.reduce((sum,idx)=>sum+state.currentGroups[idx].questions.length,0); if(state.selectedGroups.length>0){ footer.classList.remove('hidden'); el('selected-count').textContent=totalQuestions+' questions selected'; const input=el('question-count-input'); input.max=totalQuestions; input.value=totalQuestions; el('max-questions-label').textContent='/ '+totalQuestions; } else footer.classList.add('hidden'); state.selectedMode=null; state.selectedDirection=null; el('direction-selection').classList.add('hidden'); el('timer-options').classList.add('hidden'); el('start-section').classList.add('hidden'); document.querySelectorAll('.btn-mode').forEach(btn=>btn.classList.remove('active')); document.querySelectorAll('.btn-direction').forEach(btn=>btn.classList.remove('active')); }
function selectMode(mode){ state.selectedMode=mode; state.selectedDirection=null; state.extraTime=0; state.extraTimeAdded=false; document.querySelectorAll('.btn-mode').forEach(btn=>btn.classList.remove('active')); el(mode==='training'?'btn-training-mode':'btn-exam-mode').classList.add('active'); document.querySelectorAll('.btn-direction').forEach(btn=>btn.classList.remove('active')); el('direction-selection').classList.remove('hidden'); el('timer-options').classList.add('hidden'); el('start-section').classList.add('hidden'); }
function selectDirection(direction){ state.selectedDirection=direction; document.querySelectorAll('.btn-direction').forEach(btn=>btn.classList.remove('active')); el(direction==='oneway'?'btn-oneway':'btn-twoway').classList.add('active'); if(state.selectedMode==='exam'){ const count=parseInt(el('question-count-input').value,10)||0; el('base-time-display').textContent=count+' min'; el('extra-time-display').textContent='+0 min'; el('total-time-display').textContent=count+' min'; el('timer-options').classList.remove('hidden'); const btn=el('btn-add-extra'); btn.disabled=false; btn.textContent='+ إضافة 5 دقائق'; state.extraTime=0; state.extraTimeAdded=false; } else el('timer-options').classList.add('hidden'); el('start-section').classList.remove('hidden'); }
function addExtraTime(){ if(state.extraTimeAdded) return; state.extraTime=5; state.extraTimeAdded=true; const count=parseInt(el('question-count-input').value,10)||0; el('extra-time-display').textContent='+5 min'; el('total-time-display').textContent=(count+5)+' min'; const btn=el('btn-add-extra'); btn.disabled=true; btn.textContent='✓ تمت إضافة 5 دقائق'; }
function confirmStartExam(){ try{ if(!state.selectedMode || !state.selectedDirection){ showToast('يرجى اختيار النمط واتجاه التنقل.','error'); return; } const count=parseInt(el('question-count-input').value,10); if(!count || count<1){ showToast('يرجى إدخال عدد صحيح من الأسئلة.','error'); return; } let questions=[]; state.selectedGroups.forEach(idx=>{ if(state.currentGroups[idx] && Array.isArray(state.currentGroups[idx].questions)) questions=questions.concat(state.currentGroups[idx].questions); }); if(!questions.length){ showToast('لا توجد أسئلة متاحة للبدء.','error'); return; } questions=shuffleArray(questions).slice(0, count); startExamSession(questions, state.selectedMode, state.selectedDirection, state.currentSelectionMeta ? state.currentSelectionMeta.sectionType : 'custom', state.extraTime); }catch(err){ console.error('confirmStartExam error', err); showToast('حدث خطأ عند بدء الامتحان. افتح Console إن استمرت المشكلة.','error'); } }

function startExamSession(questions,mode,direction,sourceLabel,extraMinutes){ state.currentExam={ mode, direction, sourceLabel:sourceLabel||'custom', questions:questions.map(q=>Object.assign({},q)), currentIndex:0, answers:new Array(questions.length).fill(null), firstAnswers:new Array(questions.length).fill(null), startTime:Date.now(), totalTime:(questions.length+(extraMinutes||0))*60*1000, submitted:false, showAnswer:false, metaVisible:false }; saveExamState(); showScreen('exam-screen'); renderExam(); if(mode==='exam') startTimer(); scrollQuestionIntoView(false); }
function startSpecialExam(questions, mode, direction){ startExamSession(shuffleArray(questions.slice()), mode, direction||'twoway', 'special', 5); }

function renderExam(){ if(!state.currentExam) return; const t=theme(); const questions=state.currentExam.questions; const idx=state.currentExam.currentIndex; const q=questions[idx]; if(!q) return; let progressText=t.icons.progress+' '+(idx+1)+'/'+questions.length; if(state.currentExam.mode==='training'){ const answered=state.currentExam.firstAnswers.filter(x=>x!==null).length; const correct=state.currentExam.firstAnswers.filter((ans,i)=>ans!==null && isAnswerCorrect(questions[i],ans)).length; const pct=answered>0 ? Math.round((correct/answered)*100) : 0; progressText+=' · '+t.icons.success+correct+' · '+pct+'%'; } else progressText+=' · '+(questions.length-idx)+' left'; el('exam-progress').textContent=progressText; renderGrid(); const correctIdx=getCorrectIndex(q); const showAnswerState=state.currentExam.mode==='training' && state.currentExam.showAnswer; const fav=state.favorites.includes(q.id); el('question-container').innerHTML=`<div class="question-header"><span class="question-number">Q${escapeHtml(q.number||String(idx+1))}</span><div class="question-actions"><button class="icon-btn ${fav?'active':''}" onclick="toggleFavorite('${q.id}')">💚</button><button class="icon-btn" onclick="toggleQuestionLocation()">${t.icons.location}</button></div></div><p class="question-text">${escapeHtml(q.text)}</p><div class="options-list">${q.options.map((opt,i)=>{ let cls='option-btn'; if(state.currentExam.answers[idx]===i) cls+=' selected'; if(showAnswerState){ if(i===correctIdx) cls+=' correct'; else if(state.currentExam.answers[idx]===i && i!==correctIdx) cls+=' wrong'; } return '<button class="'+cls+'" onclick="selectOption('+i+')">'+escapeHtml(opt)+'</button>'; }).join('')}</div><div id="question-location-box" class="inline-meta ${state.currentExam.metaVisible?'visible':''}"><span>${t.icons.subject} ${escapeHtml(q.subjectName||'')}</span><span>${q.sourceType==='ai'?t.icons.ai:t.icons.lectures} ${escapeHtml(q.lectureName||'')}</span>${q.batchName?'<span>'+t.icons.years+' '+escapeHtml(q.batchName)+'</span>':''}${q.pageNumber?'<span>'+t.icons.location+' '+escapeHtml(q.pageNumber)+'</span>':''}</div><div class="explanation-box ${showAnswerState?'visible':''}"><strong>Explanation:</strong> ${escapeHtml(q.explanation||'No explanation available.')}</div>`; renderExamNav(); }
function renderGrid(){ if(!state.currentExam) return; const grid=el('question-grid'); grid.innerHTML=''; state.currentExam.questions.forEach((q,idx)=>{ let cls='grid-btn'; if(idx===state.currentExam.currentIndex) cls+=' current'; else if(state.currentExam.answers[idx]!==null){ if(state.currentExam.mode==='training' && state.currentExam.firstAnswers[idx]!==null) cls+=isAnswerCorrect(q,state.currentExam.firstAnswers[idx])?' answered':' wrong'; else cls+=' answered'; } if(state.currentExam.direction==='oneway' && idx<state.currentExam.currentIndex) cls+=' disabled'; const btn=document.createElement('button'); btn.className=cls; btn.textContent=String(idx+1); btn.onclick=()=>navigateToQuestion(idx); grid.appendChild(btn); }); }
function renderExamNav(){ if(!state.currentExam) return; const nav=el('exam-nav'); const idx=state.currentExam.currentIndex, last=state.currentExam.questions.length-1; let left='<span></span>', right='<span class="nav-right"></span>'; if(state.currentExam.direction==='twoway' && idx>0) left='<button class="btn-secondary" onclick="prevQuestion()">Previous ←</button>'; if(state.currentExam.mode==='training'){ if(state.currentExam.showAnswer) right=idx<last?'<button class="btn-primary nav-right" onclick="nextQuestion()">Next →</button>':'<button class="btn-primary nav-right" onclick="finishExam()">Finish</button>'; else if(state.currentExam.answers[idx]!==null) right='<button class="btn-small nav-right" onclick="showAnswer()">Show Answer</button>'; } else if(state.currentExam.answers[idx]!==null) right=idx<last?'<button class="btn-primary nav-right" onclick="nextQuestion()">Next →</button>':'<button class="btn-primary nav-right" onclick="finishExam()">Submit Exam</button>'; nav.innerHTML=left+right; }
function selectOption(optionIndex){ if(!state.currentExam || state.currentExam.submitted) return; if(state.currentExam.mode==='training' && state.currentExam.showAnswer) return; const idx=state.currentExam.currentIndex; const q=state.currentExam.questions[idx]; state.currentExam.answers[idx]=optionIndex; if(state.currentExam.firstAnswers[idx]===null) state.currentExam.firstAnswers[idx]=optionIndex; const correct=isAnswerCorrect(q,optionIndex); if(state.currentExam.mode==='training'){ if(state.settings.feedbackEnabled) playEffectSound(correct?'right':'wrong'); if(correct){ state.currentExam.showAnswer=true; if(state.settings.animations!==false) showFireworks(48,12); } else { if(!state.wrongQuestions.includes(q.id)){ state.wrongQuestions.push(q.id); saveWrongQuestions(); } showToast(themeWrongMessage(),'error'); } saveExamState(); renderExam(); } else { saveExamState(); renderExam(); } }
function themeWrongMessage(){ switch(state.settings.theme){ case 'desert': return 'الجواب انحرف عن مسار القافلة.'; case 'space': return 'Trajectory mismatch. Try again.'; case 'pirates': return 'Wrong turn on the treasure map.'; case 'castle': return 'The dragon dodged that answer.'; case 'lab': return 'Experiment unstable. Re-check the sample.'; default: return 'إجابة خاطئة.'; } }
function showAnswer(){ if(!state.currentExam) return; state.currentExam.showAnswer=true; const idx=state.currentExam.currentIndex; const q=state.currentExam.questions[idx]; const ans=state.currentExam.firstAnswers[idx]; if(ans!==null && !isAnswerCorrect(q,ans) && !state.wrongQuestions.includes(q.id)){ state.wrongQuestions.push(q.id); saveWrongQuestions(); } saveExamState(); renderExam(); }
function nextQuestion(){ if(!state.currentExam) return; if(state.currentExam.currentIndex<state.currentExam.questions.length-1){ state.currentExam.currentIndex+=1; state.currentExam.showAnswer=false; state.currentExam.metaVisible=false; saveExamState(); renderExam(); scrollQuestionIntoView(true); } }
function prevQuestion(){ if(!state.currentExam || state.currentExam.direction!=='twoway') return; if(state.currentExam.currentIndex>0){ state.currentExam.currentIndex-=1; if(state.currentExam.mode==='training') state.currentExam.showAnswer=state.currentExam.answers[state.currentExam.currentIndex]!==null; state.currentExam.metaVisible=false; saveExamState(); renderExam(); scrollQuestionIntoView(true); } }
function navigateToQuestion(index){ if(!state.currentExam) return; if(state.currentExam.direction==='oneway' && index!==state.currentExam.currentIndex) return; state.currentExam.currentIndex=index; if(state.currentExam.mode==='training') state.currentExam.showAnswer=state.currentExam.answers[index]!==null; state.currentExam.metaVisible=false; saveExamState(); renderExam(); scrollQuestionIntoView(true); }
function scrollQuestionIntoView(smooth){ const q=el('question-container'); if(!q) return; const top=q.getBoundingClientRect().top + window.scrollY - 12; window.scrollTo({top, behavior:smooth && state.settings.animations!==false ? 'smooth':'auto'}); }
function toggleQuestionLocation(){ if(!state.currentExam) return; state.currentExam.metaVisible=!state.currentExam.metaVisible; saveExamState(); const box=el('question-location-box'); if(box) box.classList.toggle('visible', state.currentExam.metaVisible); }
function toggleGrid(){ const grid=el('question-grid'); const btn=el('btn-grid-toggle'); grid.classList.toggle('hidden'); btn.innerHTML=grid.classList.contains('hidden')?'<span>☰</span> إظهار الشبكة':'<span>☰</span> إخفاء الشبكة'; }
function exitExam(){ if(state.currentExam && !state.currentExam.submitted) askConfirm('هل تريد الخروج؟ سيتم حفظ التقدم الحالي.', ()=>{ saveExamState(); state.currentExam=null; clearInterval(state.timerInterval); state.timerInterval=null; goHome(); }); else { state.currentExam=null; goHome(); } }

function startTimer(){ clearInterval(state.timerInterval); const timerEl=el('exam-timer'); timerEl.classList.remove('hidden'); state.timerInterval=setInterval(()=>{ if(!state.currentExam || state.currentExam.submitted){ clearInterval(state.timerInterval); state.timerInterval=null; return; } const elapsed=Date.now()-state.currentExam.startTime; const remaining=state.currentExam.totalTime-elapsed; if(remaining<=0){ clearInterval(state.timerInterval); state.timerInterval=null; timeUp(); return; } const mins=Math.floor(remaining/60000); const secs=Math.floor((remaining%60000)/1000); timerEl.textContent=mins+':'+String(secs).padStart(2,'0'); timerEl.classList.toggle('timer-danger', remaining<=60000); },1000); }
function timeUp(){ if(!state.currentExam) return; const unanswered=state.currentExam.answers.filter(a=>a===null).length; showToast('انتهى الوقت! يوجد '+unanswered+' سؤالًا بدون إجابة.','error'); finishExam(); }
function finishExam(){ if(!state.currentExam) return; state.currentExam.submitted=true; state.currentExam.endTime=Date.now(); if(state.currentExam.mode==='exam'){ state.currentExam.questions.forEach((q,idx)=>{ const ans=state.currentExam.answers[idx]; if(ans!==null && !isAnswerCorrect(q,ans) && !state.wrongQuestions.includes(q.id)) state.wrongQuestions.push(q.id); }); saveWrongQuestions(); } clearInterval(state.timerInterval); state.timerInterval=null; saveProgress(); clearExamState(); if(state.currentExam.mode==='exam'){ showScreen('results-screen'); showWaitingMessages(); } else showResults(); }
function saveProgress(){ if(!state.currentExam) return; const answers=state.currentExam.mode==='exam'?state.currentExam.answers:state.currentExam.firstAnswers; state.currentExam.questions.forEach((q,idx)=>{ if(answers[idx]===null) return; addProgressId('subject:'+q.subjectName,q.id); const actual=q.originalSourceType||q.sourceType; if(actual==='lecture') addProgressId('lecture:'+q.subjectName+'/'+q.lectureName,q.id); if(actual==='ai') addProgressId('ai:'+q.subjectName+'/'+q.lectureName,q.id); if(q.batchName) addProgressId('year:'+q.subjectName+'/'+q.batchName,q.id); }); saveProgressStore(); updateStatisticsIfOpen(); }
function showWaitingMessages(){ const waitDiv=el('results-waiting'), contentDiv=el('results-content'), reviewDiv=el('results-review'), messageEl=el('waiting-message'); const messages=['جاري تحليل الإجابات...','يتم احتساب النتيجة...','نراجع الأداء العام...','لحظات قليلة...','يتم تجهيز النتائج...']; waitDiv.classList.remove('hidden'); reviewDiv.classList.add('hidden'); reviewDiv.innerHTML=''; contentDiv.innerHTML=''; let idx=0; const interval=setInterval(()=>{ idx=(idx+1)%messages.length; messageEl.textContent=messages[idx]; },1500); setTimeout(()=>{ clearInterval(interval); waitDiv.classList.add('hidden'); showResults(); },2200); }
function calculateScore(exam){ const questions=exam.questions; const answers=exam.mode==='exam'?exam.answers:exam.firstAnswers; const total=questions.length; const answered=answers.filter(a=>a!==null).length; const correct=answers.reduce((sum,a,idx)=>sum + (a!==null && isAnswerCorrect(questions[idx],a) ? 1 : 0),0); return {total, answered, correct, unanswered:total-answered, incorrect:answered-correct, score: total>0 ? Math.round((correct/total)*100) : 0}; }
function showResults(){ if(!state.currentExam) return; const t=theme(); showScreen('results-screen'); el('results-title').textContent=t.icons.results+' '+t.texts.resultsTitle; const stats=calculateScore(state.currentExam); const timeSpent=state.currentExam.endTime ? Math.round((state.currentExam.endTime-state.currentExam.startTime)/1000) : 0; const mins=Math.floor(timeSpent/60), secs=timeSpent%60; if(stats.score>=50){ playCelebrateSound(); if(state.settings.animations!==false) showFireworks(110,24); } el('results-content').innerHTML=`<div class="result-score">${stats.score}%</div><div class="result-details"><div class="result-card"><div class="value">${stats.correct}/${stats.total}</div><div class="label">Correct</div></div><div class="result-card"><div class="value">${mins}m ${secs}s</div><div class="label">Time Spent</div></div><div class="result-card"><div class="value">${stats.unanswered}</div><div class="label">Unanswered</div></div><div class="result-card"><div class="value">${stats.incorrect}</div><div class="label">Incorrect</div></div></div><button class="btn-primary mt-20" onclick="reviewExam()">${t.icons.review} Review Questions</button><button class="btn-secondary mt-10" onclick="goHome()">${t.icons.exams} Back to Home</button>`; }
function reviewExam(){ if(!state.currentExam) return; const reviewDiv=el('results-review'); reviewDiv.classList.remove('hidden'); let html='<h3 class="mt-20" style="text-align:right">'+theme().icons.review+' Review</h3>'; state.currentExam.questions.forEach((q,idx)=>{ const userAnswer=state.currentExam.answers[idx]; const correctIdx=getCorrectIndex(q); const ok=userAnswer===correctIdx; html += `<div class="question-container mt-10" style="border-inline-start:4px solid ${ok?'var(--success)':'var(--danger)'};"><div class="question-header"><span class="question-number">Q${escapeHtml(q.number||String(idx+1))}</span><span style="color:${ok?'var(--success)':'var(--danger)'};font-weight:900;">${ok?theme().icons.success+' Correct':theme().icons.error+' Wrong'}</span></div><p class="question-text">${escapeHtml(q.text)}</p><div class="options-list">${q.options.map((opt,i)=>{ let cls='option-btn'; if(i===correctIdx) cls+=' correct'; if(i===userAnswer && i!==correctIdx) cls+=' wrong'; return '<div class="'+cls+'" style="cursor:default;">'+escapeHtml(opt)+'</div>'; }).join('')}</div><div class="explanation-box visible"><strong>Explanation:</strong> ${escapeHtml(q.explanation||'No explanation available.')}</div></div>`; }); reviewDiv.innerHTML=html; }

function populateSearchFilter(){ const filter=el('search-filter'); if(!filter) return; filter.innerHTML='<option value="all">All Subjects</option>'; state.subjects.forEach(s=>{ filter.innerHTML += '<option value="'+escapeHtml(s.id)+'">'+escapeHtml(s.name)+'</option>'; }); }
function performSearch(){ const query=String(el('search-input').value||'').toLowerCase().trim(); const filter=el('search-filter').value; const resultsDiv=el('search-results'); if(query.length<2){ resultsDiv.innerHTML='<p style="color:var(--text-muted); text-align:center; padding:20px;">اكتب حرفين على الأقل للبحث...</p>'; return; } const t=theme(); const results=state.allQuestions.filter(q=>{ const text=[q.text,(q.options||[]).join(' '),q.explanation||'',q.batchName||'',q.lectureName||'',q.subjectName||''].join(' ').toLowerCase(); const matches=filter==='all'||slugify(q.subjectName)===filter; return text.includes(query) && matches; }); if(!results.length){ resultsDiv.innerHTML='<p style="color:var(--text-muted); text-align:center; padding:20px;">لا توجد نتائج مطابقة.</p>'; return; } resultsDiv.innerHTML=results.slice(0,60).map(q=>`<div class="search-result-item" onclick="openReadonly('${q.id}')"><p><strong>Q${escapeHtml(q.number||'?')}:</strong> ${escapeHtml(shortenText(q.text,140))}</p><div class="search-result-meta">${t.icons.subject} ${escapeHtml(q.subjectName||'')} · ${q.sourceType==='ai'?t.icons.ai:t.icons.lectures} ${escapeHtml(q.lectureName||'')} ${q.batchName?'· '+t.icons.years+' '+escapeHtml(q.batchName):''} ${q.pageNumber?'· '+t.icons.location+' '+escapeHtml(q.pageNumber):''}</div></div>`).join(''); }
function openReadonly(questionId){ const q=state.allQuestions.find(item=>item.id===questionId); if(!q) return; const t=theme(); const correctIdx=getCorrectIndex(q); showScreen('readonly-screen'); el('readonly-content').innerHTML=`<div class="question-header"><span class="question-number">Question ${escapeHtml(q.number||'?')}</span><div class="question-actions"><button class="icon-btn ${state.favorites.includes(q.id)?'active':''}" onclick="toggleFavorite('${q.id}'); openReadonly('${q.id}')">💚</button><button class="icon-btn" onclick="showLocation('${escapeJsString(q.subjectName)}','${escapeJsString(q.lectureName)}','${escapeJsString(q.batchName||'')}','${escapeJsString(q.pageNumber||'')}')">${t.icons.location}</button></div></div><p class="question-text">${escapeHtml(q.text)}</p><div class="options-list">${q.options.map((opt,i)=>'<div class="option-btn '+(i===correctIdx?'correct':'')+'" style="cursor:default;">'+escapeHtml(opt)+'</div>').join('')}</div><div class="explanation-box visible"><strong>Explanation:</strong> ${escapeHtml(q.explanation||'No explanation available.')}</div>`; }
function closeReadonly(){ if(el('search-input') && el('search-input').value) showScreen('search-screen'); else goHome(); }
function showLocation(subjectName, lectureName, batchName, pageNumber){ const parts=[]; if(subjectName) parts.push('المادة: '+subjectName); if(lectureName) parts.push('الملف: '+lectureName); if(batchName) parts.push('الدفعة: '+batchName); if(pageNumber) parts.push('الصفحة: '+pageNumber); showToast(parts.join(' | ') || 'لا توجد بيانات موقع متاحة.','info'); }
function openSection(section){ if(section==='wrong') openWrongQuestions(); else if(section==='favorites') openFavoriteQuestions(); else if(section==='search'){ showScreen('search-screen'); el('search-input').value=''; el('search-results').innerHTML=''; } else openExams(); }
function openWrongQuestions(){ const questions=state.allQuestions.filter(q=>state.wrongQuestions.includes(q.id)); if(!questions.length){ showToast('لا توجد أسئلة خاطئة حتى الآن.','info'); return; } showScreen('selection-screen'); el('selection-title').textContent='Wrong Questions'; el('selection-search-container').classList.add('hidden'); el('selection-footer').classList.add('hidden'); el('selection-list').innerHTML=`<div class="empty-state"><p style="font-size:1.05rem;font-weight:900;margin-bottom:16px;">${questions.length} سؤالًا خاطئًا متاحًا للتدريب</p><div class="mode-buttons" style="max-width:420px;margin:0 auto;"><button class="btn-mode" onclick="startSpecialExam(getWrongQuestionObjects(),'training','twoway')"><span class="mode-icon">🎓</span><span class="mode-label">Training</span></button><button class="btn-mode" onclick="startSpecialExam(getWrongQuestionObjects(),'exam','oneway')"><span class="mode-icon">📝</span><span class="mode-label">Exam</span></button></div><button class="btn-danger mt-20" onclick="clearWrongQuestions()">مسح الأسئلة الخاطئة</button></div>`; state.currentSelectionMeta={backContext:'home'}; }
function getWrongQuestionObjects(){ return state.allQuestions.filter(q=>state.wrongQuestions.includes(q.id)); }
function clearWrongQuestions(){ askConfirm('هل تريد مسح جميع الأسئلة الخاطئة؟', ()=>{ state.wrongQuestions=[]; saveWrongQuestions(); goHome(); showToast('تم مسح قائمة الأسئلة الخاطئة.','success'); }); }
function openFavoriteQuestions(){ const questions=state.allQuestions.filter(q=>state.favorites.includes(q.id)); if(!questions.length){ showToast('لا توجد أسئلة مفضلة حتى الآن.','info'); return; } showScreen('selection-screen'); el('selection-title').textContent='Favorite Questions'; el('selection-search-container').classList.add('hidden'); el('selection-footer').classList.add('hidden'); el('selection-list').innerHTML=`<div class="empty-state"><p style="font-size:1.05rem;font-weight:900;margin-bottom:16px;">${questions.length} سؤالًا مفضلًا</p><div class="mode-buttons" style="max-width:420px;margin:0 auto;"><button class="btn-mode" onclick="startSpecialExam(getFavoriteQuestionObjects(),'training','twoway')"><span class="mode-icon">🎓</span><span class="mode-label">Training</span></button><button class="btn-mode" onclick="startSpecialExam(getFavoriteQuestionObjects(),'exam','oneway')"><span class="mode-icon">📝</span><span class="mode-label">Exam</span></button></div><button class="btn-danger mt-20" onclick="clearFavorites()">مسح المفضلة</button></div>`; state.currentSelectionMeta={backContext:'home'}; }
function getFavoriteQuestionObjects(){ return state.allQuestions.filter(q=>state.favorites.includes(q.id)); }
function clearFavorites(){ askConfirm('هل تريد مسح جميع المفضلة؟', ()=>{ state.favorites=[]; saveFavorites(); goHome(); showToast('تم مسح قائمة المفضلة.','success'); }); }
function toggleFavorite(questionId){ const idx=state.favorites.indexOf(questionId); if(idx>-1) state.favorites.splice(idx,1); else state.favorites.push(questionId); saveFavorites(); if(state.currentExam && !state.currentExam.submitted) renderExam(); updateStatisticsIfOpen(); }

function getGroupProgressKey(type, subjectName, groupName){ return type+':'+subjectName+'/'+groupName; }
function getAnsweredCountForKey(key){ const entry=state.progress[key]||{questionIds:[]}; return new Set(entry.questionIds||[]).size; }
function getSectionSummary(subject, type){ const groups = type==='lecture' ? subject.lectures : type==='ai' ? subject.ai : subject.years; const totalQuestions = groups.reduce((sum,g)=>sum+g.questions.length,0); let answered = 0; groups.forEach(g=>answered += getAnsweredCountForKey(getGroupProgressKey(type, subject.name, g.name))); const pct = totalQuestions ? Math.round((answered/totalQuestions)*100) : 0; return { groups, totalQuestions, answered, pct }; }
function toggleStatistics(){ const panel=el('statistics-panel'); panel.classList.toggle('visible'); if(panel.classList.contains('visible')) renderStatistics(); }
function updateStatisticsIfOpen(){ const panel=el('statistics-panel'); if(panel && panel.classList.contains('visible')) renderStatistics(); }
function toggleStatsSubject(subjectId){ state.statsExpand.subjects[subjectId] = !state.statsExpand.subjects[subjectId]; renderStatistics(); }
function toggleStatsSection(key){ state.statsExpand.sections[key] = !state.statsExpand.sections[key]; renderStatistics(); }
function renderStatistics(){
  const t=theme();
  const ordered=sortSubjects(state.subjects);
  const answeredQuestions=new Set();
  Object.keys(state.progress).forEach(key=>{ const entry=state.progress[key]||{questionIds:[]}; (entry.questionIds||[]).forEach(id=>answeredQuestions.add(id)); });
  const totalQuestions=state.allQuestions.length;
  const summaryHtml=`<div class="stats-summary-grid"><div class="progress-card"><h4>${t.icons.progress} الإجمالي</h4><p><span>كل الأسئلة</span><strong>${totalQuestions}</strong></p><p><span>تمت الإجابة</span><strong>${answeredQuestions.size}</strong></p></div><div class="progress-card"><h4>${t.icons.favorites} المفضلة</h4><p><span>عدد الأسئلة</span><strong>${state.favorites.length}</strong></p></div><div class="progress-card"><h4>${t.icons.wrong} الأسئلة الخاطئة</h4><p><span>عدد الأسئلة</span><strong>${state.wrongQuestions.length}</strong></p></div></div>`;
  const subjectCards = ordered.map(subject=>{
    const subjectKey='subject:'+subject.name;
    const answered = getAnsweredCountForKey(subjectKey);
    const pct = subject.totalQuestions ? Math.round((answered/subject.totalQuestions)*100) : 0;
    const isExpanded = !!state.statsExpand.subjects[subject.id];
    const sectionCards = [];
    const typesToRender = [
      { enabled: state.statsSettings.lectures, type:'lecture', label:'Lectures', icon:t.icons.lectures },
      { enabled: state.statsSettings.years, type:'year', label:'Years', icon:t.icons.years },
      { enabled: state.statsSettings.ai, type:'ai', label:'AI', icon:t.icons.ai }
    ];
    typesToRender.forEach(item=>{
      if(!item.enabled) return;
      const summary = getSectionSummary(subject, item.type);
      if(!summary.groups.length) return;
      const sectionKey = subject.id + '__' + item.type;
      const open = !!state.statsExpand.sections[sectionKey];
      const groupsHtml = summary.groups.map(group=>{
        const answeredGroup = getAnsweredCountForKey(getGroupProgressKey(item.type, subject.name, group.name));
        const pctGroup = group.questions.length ? Math.round((answeredGroup/group.questions.length)*100) : 0;
        return `<div class="stats-lecture-row"><div><strong>${escapeHtml(group.name)}</strong></div><div class="stats-meta-pill">${group.questions.length} سؤال</div><div class="stats-meta-pill">${pctGroup}%</div></div>`;
      }).join('');
      sectionCards.push(`<div class="stats-section-card ${open?'expanded':''}" onclick="toggleStatsSection('${sectionKey}')"><div class="stats-section-head"><div class="stats-section-title">${item.icon} ${item.label}</div><div class="stats-meta-pill">${summary.totalQuestions} سؤال</div><div class="stats-meta-pill">${summary.pct}%</div><div class="stats-expand-icon">${open?'▾':'▸'}</div></div><div class="stats-section-details"><div class="stats-lecture-list">${groupsHtml}</div></div></div>`);
    });
    const detailHtml = sectionCards.length ? `<div class="stats-subject-details"><div class="section-breakdown">${sectionCards.join('')}</div></div>` : `<div class="stats-subject-details"><div class="stats-empty-note">لا توجد أقسام ظاهرة حسب إعدادات الإحصائيات أو لا توجد ملفات متاحة.</div></div>`;
    return `<div class="stats-subject-card ${isExpanded?'expanded':''}" onclick="toggleStatsSubject('${subject.id}')"><div class="stats-subject-head"><div class="stats-subject-title">${t.icons.subject} ${escapeHtml(subject.name)}</div><div class="stats-meta-pill">${subject.totalQuestions} سؤال</div><div class="stats-meta-pill">${pct}%</div><div class="stats-expand-icon">${isExpanded?'▾':'▸'}</div></div>${detailHtml}</div>`;
  }).join('');
  el('stats-content').innerHTML = summaryHtml + '<div class="progress-grid">' + (subjectCards || '<div class="empty-state"><p>لا توجد بيانات إحصائية بعد.</p></div>') + '</div>';
}
function resetProgress(){ askConfirm('هل تريد إعادة ضبط جميع البيانات؟ لا يمكن التراجع عن هذا الإجراء.', ()=>{ state.progress={}; state.favorites=[]; state.wrongQuestions=[]; localStorage.removeItem(STORAGE_KEYS.progress); localStorage.removeItem(STORAGE_KEYS.favorites); localStorage.removeItem(STORAGE_KEYS.wrong); localStorage.removeItem(STORAGE_KEYS.examState); showToast('تمت إعادة ضبط جميع البيانات.','success'); updateStatisticsIfOpen(); }); }

function showFireworks(durationFrames=80, explosionCount=18){ const canvas=el('fireworks-canvas'); if(!canvas) return; canvas.classList.remove('hidden'); const ctx=canvas.getContext('2d'); canvas.width=window.innerWidth; canvas.height=window.innerHeight; const palettes={default:['#2563eb','#38bdf8','#10b981','#f59e0b'],desert:['#f4c95d','#db9b41','#9a5b24','#fff0c9'],space:['#8b5cf6','#38bdf8','#f0abfc','#ffffff'],pirates:['#d9a740','#7d4b16','#fdf0c2','#7ec8e3'],castle:['#d4af37','#7c3f98','#f5f1dc','#9ea7d8'],lab:['#00bcd4','#7ef9ff','#15d3a2','#ffffff']}; const colors=palettes[state.settings.theme]||palettes.default; const particles=[]; const bursts=[{x:canvas.width*.3,y:canvas.height*.35},{x:canvas.width*.7,y:canvas.height*.4},{x:canvas.width*.5,y:canvas.height*.26}]; bursts.forEach(b=>{ for(let i=0;i<explosionCount;i++){ const angle=(Math.PI*2*i)/explosionCount; const speed=2.5+Math.random()*4.8; particles.push({x:b.x,y:b.y,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,color:colors[Math.floor(Math.random()*colors.length)],size:Math.random()*3+1.5,life:1}); } }); let frame=0; function animate(){ ctx.clearRect(0,0,canvas.width,canvas.height); particles.forEach(p=>{ p.x+=p.vx; p.y+=p.vy; p.vy+=0.08; p.life-=0.012; if(p.life>0){ ctx.globalAlpha=p.life; ctx.fillStyle=p.color; ctx.beginPath(); ctx.arc(p.x,p.y,p.size,0,Math.PI*2); ctx.fill(); } }); frame++; if(frame<durationFrames) requestAnimationFrame(animate); else { ctx.clearRect(0,0,canvas.width,canvas.height); canvas.classList.add('hidden'); } } animate(); }

function goHome(){ toggleExamSettings(false); toggleStatisticsSettings(false); showScreen('home-screen'); const review=el('results-review'); if(review) review.classList.add('hidden'); }
function checkResumeExam(){ const raw=localStorage.getItem(STORAGE_KEYS.examState); if(!raw) return; try{ const saved=JSON.parse(raw); if(!saved || saved.submitted || !Array.isArray(saved.questions) || !saved.questions.length){ clearExamState(); return; } askConfirm('يوجد امتحان غير مكتمل. هل تريد المتابعة من حيث توقفت؟', ()=>{ state.currentExam=saved; showScreen('exam-screen'); renderExam(); if(state.currentExam.mode==='exam') startTimer(); }, ()=>clearExamState()); }catch{ clearExamState(); } }

window.addEventListener('DOMContentLoaded', async ()=>{
  loadSettings(); loadProgress(); loadFavorites(); loadWrongQuestions(); loadSubjectPreferences(); loadStatsSettings();
  applySettings();
  const quotes=['لا توجد وصفة سحرية، ولا توجد طريقة ليس فيها العمل والتعب وبذل الجهد!','الفشل ليس النهاية، بل خطوة ضرورية نحو القمة إذا تعلمت منه.','العلم الذي تدرسه اليوم هو الأمل الذي ستمنحه لغيرك غدًا.','دراسة الطب ماراثون وليست سباقًا قصيرًا؛ واصل التقدم بهدوء.','ابدأ الآن، فالوقت المثالي لا يأتي وحده.'];
  el('random-quote').textContent=quotes[Math.floor(Math.random()*quotes.length)];
  document.addEventListener('click',e=>{ if(!e.target.closest('.subject-card')) closeSubjectActions(); });
  primeAudioUnlock(); await prepareStaticEffectAudio();
  try{ await loadData(); }catch(err){ console.error(err); renderSubjects(); showToast('تعذر تحميل بيانات GitHub الآن. تحقّق من الاتصال أو بنية المجلدات.','error'); }
  checkResumeExam();
});

window.state=state;
window.openExams=openExams; window.openSection=openSection; window.toggleStatistics=toggleStatistics; window.toggleSettings=toggleSettings; window.toggleDarkMode=toggleDarkMode; window.changeTheme=changeTheme; window.changeSound=changeSound; window.toggleBackgroundSoundEnabled=toggleBackgroundSoundEnabled; window.changeVolume=changeVolume; window.toggleFeedbackSounds=toggleFeedbackSounds; window.toggleAnimations=toggleAnimations; window.filterSubjects=filterSubjects; window.handleSubjectOpen=handleSubjectOpen; window.startSubjectLongPress=startSubjectLongPress; window.cancelSubjectLongPress=cancelSubjectLongPress; window.moveSubject=moveSubject; window.togglePinSubject=togglePinSubject; window.openSubject=openSubject; window.openSubjectCategory=openSubjectCategory; window.backFromSelection=backFromSelection; window.filterSelectionList=filterSelectionList; window.toggleGroupSelection=toggleGroupSelection; window.selectMode=selectMode; window.selectDirection=selectDirection; window.addExtraTime=addExtraTime; window.confirmStartExam=confirmStartExam; window.startSpecialExam=startSpecialExam; window.selectOption=selectOption; window.showAnswer=showAnswer; window.nextQuestion=nextQuestion; window.prevQuestion=prevQuestion; window.navigateToQuestion=navigateToQuestion; window.toggleGrid=toggleGrid; window.exitExam=exitExam; window.finishExam=finishExam; window.reviewExam=reviewExam; window.performSearch=performSearch; window.openReadonly=openReadonly; window.closeReadonly=closeReadonly; window.showLocation=showLocation; window.toggleQuestionLocation=toggleQuestionLocation; window.openWrongQuestions=openWrongQuestions; window.getWrongQuestionObjects=getWrongQuestionObjects; window.clearWrongQuestions=clearWrongQuestions; window.toggleFavorite=toggleFavorite; window.openFavoriteQuestions=openFavoriteQuestions; window.getFavoriteQuestionObjects=getFavoriteQuestionObjects; window.clearFavorites=clearFavorites; window.resetProgress=resetProgress; window.goHome=goHome; window.toggleExamSettings=toggleExamSettings; window.toggleStatisticsSettings=toggleStatisticsSettings; window.updateStatisticsType=updateStatisticsType; window.toggleStatsSubject=toggleStatsSubject; window.toggleStatsSection=toggleStatsSection; window.hideDialog=hideDialog; window.dialogConfirmAction=dialogConfirmAction; window.dialogCancelAction=dialogCancelAction;
