const state = {
  subjects: [], displayedSubjects: [], allQuestions: [], currentSubject: null, currentSelectionMeta: null,
  currentGroups: [], selectedGroups: [], selectedMode: null, selectedDirection: null, extraTime: 0, extraTimeAdded: false,
  currentExam: null, favorites: [], wrongQuestions: [], progress: {},
  settings: {}, subjectPreferences: { order: [], pinned: [] }, discoveredRepo: null,
  browseMode: 'all',
  statsSettings: { lectures: true, years: true, ai: true },
  statsExpand: { subjects: {}, sections: {} },
  questionsFirstSeen: {}, examHistory: [], firstVisit: null,
  toastTimer: null, timerInterval: null, audioUnlocked: false, longPressTimer: null, openSubjectActionId: null,
  dialog: { onConfirm: null, onCancel: null }
};
const STORAGE_KEYS = {
  settings:'medical-app-settings-v11', progress:'medical-app-progress-v11', favorites:'medical-app-favorites-v11', wrong:'medical-app-wrong-v11',
  examState:'medical-app-exam-state-v11', subjectPrefs:'medical-app-subject-prefs-v11', statsPrefs:'medical-app-stats-prefs-v11',
  questionLog:'medical-app-question-log-v11', examHistory:'medical-app-exam-history-v11', firstVisit:'medical-app-first-visit-v11'
};
const DEFAULT_SETTINGS = { darkMode:false, theme:'default', bgSound:'none', bgSoundEnabled:true, volume:50, feedbackEnabled:true, animations:true };
const IGNORE_ROOT_DIRS = new Set(['.git','.github','node_modules','assets','asset','audio','audios','img','images','css','js','docs','dist','build']);
const BACKGROUND_SOUNDS = { none:{file:''}, cafeteria:{file:'Cafeteria.mp3'}, 'after-exam':{file:'After the exam.mp3'}, beach:{file:'Beach.mp3'}, forest:{file:'Forest.mp3'}, fireplace:{file:'Fireplace.mp3'}, 'rain-thunder':{file:'Rain-thunder.mp3'}, 'rain-window':{file:'Rain-window.mp3'} };
const THEMES = {
 default:{icons:{exams:'📝',wrong:'❌',favorites:'⭐',search:'🔍',statistics:'📊',settings:'⚙️',lectures:'📚',ai:'🤖',years:'📅',start:'🚀',results:'🏆',progress:'🎯',location:'📍',success:'✅',error:'❌',review:'🧾',subject:'📘'},texts:{startExam:'🚀 Start Exam',resultsTitle:'Results',statsTitle:'📊 الإحصائيات',settingsTitle:'⚙️ الإعدادات',examSettingsTitle:'⚙️ Exam Settings',examSettingsButton:'⚙️ Exam Settings',trainingLabel:'Training Mode',examLabel:'Real Exam Mode'}},
 desert:{icons:{exams:'🏹',wrong:'🦂',favorites:'🌵',search:'🔎',statistics:'🧭',settings:'🏕️',lectures:'📜',ai:'🔥',years:'📅',start:'🐪',results:'👑',progress:'🏹',location:'🧭',success:'🤎',error:'🦂',review:'📜',subject:'🏜️'},texts:{startExam:'🐪 Start Journey',resultsTitle:'Majlis Report',statsTitle:'🧭 إحصائيات الرحلة',settingsTitle:'🏕️ إعدادات الخيمة',examSettingsTitle:'🏕️ Exam Camp Settings',examSettingsButton:'🏕️ Exam Settings',trainingLabel:'Training Camp',examLabel:'Journey Exam'}},
 space:{icons:{exams:'🚀',wrong:'☄️',favorites:'🌟',search:'🔭',statistics:'📡',settings:'🤖',lectures:'🛰️',ai:'👽',years:'🪐',start:'🚀',results:'🌌',progress:'🎯',location:'📡',success:'✨',error:'☄️',review:'🧾',subject:'🪐'},texts:{startExam:'🚀 Launch Mission',resultsTitle:'Mission Report',statsTitle:'📡 Mission Analytics',settingsTitle:'🤖 Space Controls',examSettingsTitle:'🤖 Mission Controls',examSettingsButton:'🤖 Mission Settings',trainingLabel:'Training Mission',examLabel:'Space Mission'}},
 pirates:{icons:{exams:'☠️',wrong:'🦈',favorites:'💰',search:'🔎',statistics:'🧭',settings:'⚓',lectures:'🗺️',ai:'🦜',years:'🗓️',start:'☠️',results:'👑',progress:'🏴‍☠️',location:'🧭',success:'🪙',error:'🦈',review:'📜',subject:'⚓'},texts:{startExam:'☠️ Start Voyage',resultsTitle:'Treasure Report',statsTitle:'🧭 Voyage Progress',settingsTitle:'⚓ Captain Settings',examSettingsTitle:'⚓ Voyage Settings',examSettingsButton:'⚓ Voyage Settings',trainingLabel:'Deck Training',examLabel:'Treasure Voyage'}},
 castle:{icons:{exams:'⚔️',wrong:'🐉',favorites:'👑',search:'🔎',statistics:'🛡️',settings:'🏰',lectures:'📜',ai:'🕯️',years:'📅',start:'⚔️',results:'👑',progress:'🏹',location:'🛡️',success:'🛡️',error:'🐉',review:'📜',subject:'🏰'},texts:{startExam:'⚔️ Begin Quest',resultsTitle:'Kingdom Report',statsTitle:'🛡️ Quest Progress',settingsTitle:'🏰 Castle Settings',examSettingsTitle:'🏰 Quest Settings',examSettingsButton:'🏰 Quest Settings',trainingLabel:'Knight Training',examLabel:'Kingdom Trial'}},
 lab:{icons:{exams:'🧪',wrong:'☣️',favorites:'🧬',search:'🔬',statistics:'📈',settings:'⚗️',lectures:'🔬',ai:'🧠',years:'📅',start:'🧪',results:'🏅',progress:'🧫',location:'📍',success:'🧫',error:'☣️',review:'📋',subject:'⚗️'},texts:{startExam:'🧪 Start Experiment',resultsTitle:'Research Report',statsTitle:'📈 Experiment Progress',settingsTitle:'⚗️ Lab Settings',examSettingsTitle:'⚗️ Experiment Settings',examSettingsButton:'⚗️ Experiment Settings',trainingLabel:'Trial Run',examLabel:'Main Experiment'}}
};

function el(id){ return document.getElementById(id); }
function theme(){ return THEMES[state.settings.theme] || THEMES.default; }
function isDarkTheme(){ return ['space','castle','lab'].includes(state.settings.theme); }
function showScreen(id){ document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active')); const t=el(id); if(t) t.classList.add('active'); }
function slugify(text){ return String(text||'').toLowerCase().replace(/[^a-z0-9\u0600-\u06FF]+/g,'-').replace(/^-+|-+$/g,'') || 'item'; }
function hashString(input){ let h=0; const s=String(input||''); for(let i=0;i<s.length;i++){ h=((h<<5)-h)+s.charCodeAt(i); h|=0; } return Math.abs(h).toString(36); }
function escapeHtml(v){ return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;'); }
function escapeAttribute(v){ return escapeHtml(v); }
function escapeJsString(v){ return String(v==null?'':v).replace(/\\/g,'\\\\').replace(/'/g,"\\'"); }
function shortenText(t,m){ const s=String(t||''); return s.length>m ? s.slice(0,m).trim()+'...' : s; }
function clampNum(v,min,max,fallback){ return Number.isNaN(v)?fallback:Math.min(max,Math.max(min,v)); }
function shuffleArray(arr){ const a=arr.slice(); for(let i=a.length-1;i>0;i--){ const j=Math.floor(Math.random()*(i+1)); [a[i],a[j]]=[a[j],a[i]]; } return a; }
function formatDateTime(ts){ const d=new Date(ts); return d.toLocaleString('ar-EG'); }
function formatDuration(ms){ const sec=Math.round((ms||0)/1000); const h=Math.floor(sec/3600), m=Math.floor((sec%3600)/60), s=sec%60; const parts=[]; if(h) parts.push(h+' ساعة'); if(m) parts.push(m+' دقيقة'); parts.push(s+' ثانية'); return parts.join(' '); }
function normalizeComparisonText(text){ return String(text||'').toLowerCase().replace(/^[a-e][\)\.\-]\s*/i,'').replace(/\s+/g,' ').trim(); }
function isPageLine(line){ return /^P\s*\(?\s*\d+\s*\)?$/i.test(line) || /^Page\s*\d+$/i.test(line); }
function isBatchLine(line){ return /^[A-Za-z][A-Za-z0-9\s&()'\/]+-\s*\d+$/i.test(line) || /^\d+(st|nd|rd|th)\s+Year/i.test(line); }
function looksLikeMetadataTail(line){ return /^[A-Za-z].{0,60}$/.test(line) && /\d/.test(line) && !/[?.!]$/.test(line); }
function isMetadataLine(line){ return isPageLine(line) || isBatchLine(line) || looksLikeMetadataTail(line); }
function resolveCorrectIndex(options, correctAnswer){ if(!Array.isArray(options)||!options.length) return -1; const m=String(correctAnswer||'').match(/^([A-E])/i); if(m){ const ix=m[1].toUpperCase().charCodeAt(0)-65; if(ix>=0&&ix<options.length) return ix; } const ans=normalizeComparisonText(correctAnswer); for(let i=0;i<options.length;i++){ const opt=normalizeComparisonText(options[i]); if(opt && (opt.includes(ans)||ans.includes(opt))) return i; } return -1; }
function getCorrectIndex(q){ if(typeof q.correctIndex==='number' && q.correctIndex>=0) return q.correctIndex; q.correctIndex=resolveCorrectIndex(q.options||[], q.correctAnswer||''); return q.correctIndex; }
function isAnswerCorrect(q, idx){ return getCorrectIndex(q)===idx; }
function getSubjectColor(subjectName){ const darkPalette=['#93c5fd','#86efac','#fcd34d','#c4b5fd','#fda4af','#67e8f9','#fdba74','#f9a8d4']; const lightPalette=['#1d4ed8','#15803d','#b45309','#7c3aed','#be123c','#0f766e','#9a3412','#9d174d']; const palette=isDarkTheme()?darkPalette:lightPalette; const subjects=sortSubjects(state.subjects).map(s=>s.name); const idx=Math.max(0, subjects.indexOf(subjectName)) % palette.length; return palette[idx]; }
function formatHistorySubLabel(item){ if(!item || !item.groups || !item.groups.length) return item.sourceLabel || 'عام'; return item.groups.map(g=>g.type==='ai' ? `${g.name} (AI)` : g.name).join('، '); }

function loadJSON(key, fallback){ try{ return JSON.parse(localStorage.getItem(key)) || fallback; }catch{ return fallback; } }
function saveSettings(){ localStorage.setItem(STORAGE_KEYS.settings, JSON.stringify(state.settings)); }
function loadSettings(){ state.settings=Object.assign({}, DEFAULT_SETTINGS, loadJSON(STORAGE_KEYS.settings, {})); }
function saveFavorites(){ localStorage.setItem(STORAGE_KEYS.favorites, JSON.stringify(state.favorites)); }
function loadFavorites(){ state.favorites=loadJSON(STORAGE_KEYS.favorites, []); }
function saveWrongQuestions(){ localStorage.setItem(STORAGE_KEYS.wrong, JSON.stringify(state.wrongQuestions)); }
function loadWrongQuestions(){ state.wrongQuestions=loadJSON(STORAGE_KEYS.wrong, []); }
function saveProgressStore(){ localStorage.setItem(STORAGE_KEYS.progress, JSON.stringify(state.progress)); }
function loadProgress(){ state.progress=loadJSON(STORAGE_KEYS.progress, {}); }
function saveExamState(){ if(state.currentExam) localStorage.setItem(STORAGE_KEYS.examState, JSON.stringify(state.currentExam)); }
function clearExamState(){ localStorage.removeItem(STORAGE_KEYS.examState); }
function saveSubjectPreferences(){ localStorage.setItem(STORAGE_KEYS.subjectPrefs, JSON.stringify(state.subjectPreferences)); }
function loadSubjectPreferences(){ state.subjectPreferences=Object.assign({order:[],pinned:[]}, loadJSON(STORAGE_KEYS.subjectPrefs, {})); }
function saveStatsSettings(){ localStorage.setItem(STORAGE_KEYS.statsPrefs, JSON.stringify(state.statsSettings)); }
function loadStatsSettings(){ state.statsSettings=Object.assign({lectures:true,years:true,ai:true}, loadJSON(STORAGE_KEYS.statsPrefs, {})); }
function saveMemoryStores(){ localStorage.setItem(STORAGE_KEYS.questionLog, JSON.stringify(state.questionsFirstSeen)); localStorage.setItem(STORAGE_KEYS.examHistory, JSON.stringify(state.examHistory)); if(state.firstVisit) localStorage.setItem(STORAGE_KEYS.firstVisit, String(state.firstVisit)); }
function loadMemoryStores(){ state.questionsFirstSeen = loadJSON(STORAGE_KEYS.questionLog, {}); state.examHistory = loadJSON(STORAGE_KEYS.examHistory, []); const fv = localStorage.getItem(STORAGE_KEYS.firstVisit); state.firstVisit = fv ? Number(fv) : Date.now(); if(!fv) localStorage.setItem(STORAGE_KEYS.firstVisit, String(state.firstVisit)); }
function addProgressId(key, qid){ if(!state.progress[key]) state.progress[key]={questionIds:[]}; if(!state.progress[key].questionIds.includes(qid)) state.progress[key].questionIds.push(qid); }

function normalizeSubjectPreferences(){ const ids=state.subjects.map(s=>s.id); state.subjectPreferences.order=(state.subjectPreferences.order||[]).filter(id=>ids.includes(id)); state.subjectPreferences.pinned=(state.subjectPreferences.pinned||[]).filter(id=>ids.includes(id)); ids.forEach(id=>{ if(!state.subjectPreferences.order.includes(id)) state.subjectPreferences.order.push(id); }); saveSubjectPreferences(); }
function sortSubjects(list){ const orderMap=new Map(); (state.subjectPreferences.order||[]).forEach((id,idx)=>orderMap.set(id,idx)); const pinned=new Set(state.subjectPreferences.pinned||[]); return list.slice().sort((a,b)=>{ const ap=pinned.has(a.id)?1:0, bp=pinned.has(b.id)?1:0; if(ap!==bp) return bp-ap; const ao=orderMap.has(a.id)?orderMap.get(a.id):Number.MAX_SAFE_INTEGER; const bo=orderMap.has(b.id)?orderMap.get(b.id):Number.MAX_SAFE_INTEGER; if(ao!==bo) return ao-bo; return a.name.localeCompare(b.name,'en',{sensitivity:'base'}); }); }

function applyThemeUI(){ const t=theme(); el('nav-icon-exams').textContent=t.icons.exams; el('nav-icon-wrong').textContent=t.icons.wrong; el('nav-icon-favorites').textContent=t.icons.favorites; el('nav-icon-search').textContent=t.icons.search; el('nav-icon-statistics').textContent=t.icons.statistics; el('nav-icon-settings').textContent=t.icons.settings; if(el('nav-icon-memories')) el('nav-icon-memories').textContent='📖'; el('statistics-title').textContent=t.texts.statsTitle; el('settings-title').textContent=t.texts.settingsTitle; el('exam-settings-title').textContent=t.texts.examSettingsTitle; el('btn-exam-settings').textContent=t.texts.examSettingsButton; el('btn-start-exam').textContent=t.texts.startExam; const a=document.querySelector('#btn-training-mode .mode-label'); const b=document.querySelector('#btn-exam-mode .mode-label'); if(a) a.textContent=t.texts.trainingLabel; if(b) b.textContent=t.texts.examLabel; }
function syncSettingsControls(){ const entries=[['dark-mode-toggle','checked',!!state.settings.darkMode],['theme-selector','value',state.settings.theme],['exam-theme-selector','value',state.settings.theme],['sound-selector','value',state.settings.bgSound],['exam-sound-selector','value',state.settings.bgSound],['bg-sound-enabled-toggle','checked',state.settings.bgSoundEnabled!==false],['exam-bg-sound-enabled-toggle','checked',state.settings.bgSoundEnabled!==false],['volume-control','value',state.settings.volume],['exam-volume-control','value',state.settings.volume],['feedback-toggle','checked',state.settings.feedbackEnabled!==false],['exam-feedback-toggle','checked',state.settings.feedbackEnabled!==false],['animations-toggle','checked',state.settings.animations!==false],['stats-show-lectures','checked',state.statsSettings.lectures!==false],['stats-show-years','checked',state.statsSettings.years!==false],['stats-show-ai','checked',state.statsSettings.ai!==false]]; entries.forEach(([id,prop,val])=>{ const x=el(id); if(x) x[prop]=val; }); }
async function resolveAssetPath(candidates){ for(const item of candidates.filter(Boolean)){ try{ const u=encodeURI(item); const r=await fetch(u,{method:'HEAD'}); if(r.ok) return u; }catch(e){} } return encodeURI(candidates.find(Boolean)||''); }
async function applyBackgroundSound(){ const audio=el('bg-audio'); if(!audio) return; audio.volume=(state.settings.volume||50)/100; const key=state.settings.bgSound||'none'; const sound=BACKGROUND_SOUNDS[key]||BACKGROUND_SOUNDS.none; if(!state.settings.bgSoundEnabled || key==='none' || !sound.file){ audio.pause(); return; } const src=await resolveAssetPath([sound.file,'audio/'+sound.file,'assets/audio/'+sound.file]); if(audio.dataset.currentSrc!==src){ audio.src=src; audio.dataset.currentSrc=src; audio.load(); } if(state.audioUnlocked) audio.play().catch(()=>{}); }
function applyEffectAudioVolumes(){ ['right-audio','wrong-audio','celebrate-audio'].forEach(id=>{ const a=el(id); if(a) a.volume=(state.settings.volume||50)/100; }); }
async function prepareStaticEffectAudio(){ el('right-audio').src=await resolveAssetPath(['right.mp3','audio/right.mp3','assets/audio/right.mp3']); el('wrong-audio').src=await resolveAssetPath(['wrong.mp3','audio/wrong.mp3','assets/audio/wrong.mp3']); el('celebrate-audio').src=await resolveAssetPath(['celebrate.mp3','audio/celebrate.mp3','assets/audio/celebrate.mp3']); applyEffectAudioVolumes(); }
function primeAudioUnlock(){ function unlock(){ if(state.audioUnlocked) return; state.audioUnlocked=true; applyBackgroundSound(); document.removeEventListener('click',unlock); document.removeEventListener('touchstart',unlock); document.removeEventListener('keydown',unlock); } document.addEventListener('click',unlock,{once:true}); document.addEventListener('touchstart',unlock,{once:true}); document.addEventListener('keydown',unlock,{once:true}); }
function playEffectSound(kind){ if(!state.currentExam || state.currentExam.mode!=='training' || state.settings.feedbackEnabled===false) return; const a=el(kind==='right'?'right-audio':'wrong-audio'); if(!a||!a.src) return; try{ a.currentTime=0; a.play().catch(()=>{}); }catch(e){} }
function playCelebrateSound(){ const a=el('celebrate-audio'); if(!a||!a.src) return; try{ a.currentTime=0; a.play().catch(()=>{}); }catch(e){} }

function applySettings(){ state.settings=Object.assign({},DEFAULT_SETTINGS,state.settings||{}); document.documentElement.setAttribute('data-dark', String(!!state.settings.darkMode)); document.documentElement.setAttribute('data-theme', state.settings.theme||'default'); document.documentElement.setAttribute('data-animations', String(state.settings.animations!==false)); syncSettingsControls(); applyThemeUI(); applyBackgroundSound(); applyEffectAudioVolumes(); }
function changeTheme(name){ state.settings.theme = THEMES[name] ? name : 'default'; saveSettings(); applySettings(); renderSubjects(); if(state.currentSubject && el('subject-sections-screen').classList.contains('active')) openSubject(state.currentSubject.id); if(state.currentExam && el('exam-screen').classList.contains('active')) renderExam(); updateStatisticsIfOpen(); renderMemories(); }
function changeSound(name){ state.settings.bgSound = BACKGROUND_SOUNDS[name] ? name : 'none'; saveSettings(); applySettings(); }
function changeVolume(v){ state.settings.volume=clampNum(parseInt(v,10),0,100,50); saveSettings(); applySettings(); }
function toggleDarkMode(){ state.settings.darkMode=!!el('dark-mode-toggle').checked; saveSettings(); applySettings(); }
function toggleBackgroundSoundEnabled(){ const src=document.activeElement && (document.activeElement.id==='exam-bg-sound-enabled-toggle' || document.activeElement.id==='bg-sound-enabled-toggle') ? document.activeElement : el('bg-sound-enabled-toggle'); state.settings.bgSoundEnabled=!!src.checked; saveSettings(); applySettings(); }
function toggleFeedbackSounds(){ const src=document.activeElement && (document.activeElement.id==='exam-feedback-toggle' || document.activeElement.id==='feedback-toggle') ? document.activeElement : el('feedback-toggle'); state.settings.feedbackEnabled=!!src.checked; saveSettings(); applySettings(); }
function toggleAnimations(){ state.settings.animations=!!el('animations-toggle').checked; saveSettings(); applySettings(); }
function toggleSettings(){ el('settings-panel').classList.toggle('visible'); }
function toggleExamSettings(show){ el('exam-settings-modal').classList.toggle('hidden', !show); if(show) syncSettingsControls(); }
function toggleStatisticsSettings(show){ el('stats-settings-modal').classList.toggle('hidden', !show); if(show) syncSettingsControls(); }
function updateStatisticsType(kind, checked){ state.statsSettings[kind]=!!checked; saveStatsSettings(); syncSettingsControls(); updateStatisticsIfOpen(); }

function showToast(message, kind='info', duration=2600){ const toast=el('toast'); clearTimeout(state.toastTimer); const prefix=(theme().icons[kind] || theme().icons.statistics || 'ℹ️'); toast.textContent=prefix+' '+message; toast.classList.remove('hidden'); toast.classList.add('visible'); state.toastTimer=setTimeout(()=>{ toast.classList.remove('visible'); toast.classList.add('hidden'); },duration); }
function showDialog({title='تنبيه', message='', showCancel=false, confirmText='موافق', cancelText='إلغاء', onConfirm=null, onCancel=null}){ el('dialog-title').textContent=title; el('dialog-body').innerHTML=message; const cancel=el('dialog-cancel'); const confirm=el('dialog-confirm'); cancel.classList.toggle('hidden', !showCancel); cancel.textContent=cancelText; confirm.textContent=confirmText; state.dialog.onConfirm=onConfirm; state.dialog.onCancel=onCancel; el('dialog-overlay').classList.remove('hidden'); }
function hideDialog(){ el('dialog-overlay').classList.add('hidden'); state.dialog.onConfirm=null; state.dialog.onCancel=null; }
function dialogConfirmAction(){ const fn=state.dialog.onConfirm; hideDialog(); if(typeof fn==='function') fn(); }
function dialogCancelAction(){ const fn=state.dialog.onCancel; hideDialog(); if(typeof fn==='function') fn(); }
function askConfirm(message,onConfirm,onCancel){ showDialog({title:'تأكيد',message,showCancel:true,confirmText:'تأكيد',cancelText:'إلغاء',onConfirm,onCancel}); }

function getCurrentBrowseSubjects(){
  if(state.browseMode==='all') return sortSubjects(state.subjects);
  const idSet = new Set(state.browseMode==='favorites' ? state.favorites : state.wrongQuestions);
  const filtered = state.subjects.map(subject => {
    const reduceGroups = groups => groups.map(g => ({...g, questions:g.questions.filter(q=>idSet.has(q.id))})).filter(g=>g.questions.length>0);
    const lectures = reduceGroups(subject.lectures || []);
    const years = reduceGroups(subject.years || []);
    const ai = reduceGroups(subject.ai || []);
    const all = lectures.flatMap(g=>g.questions).concat(years.flatMap(g=>g.questions)).concat(ai.flatMap(g=>g.questions));
    return {...subject, lectures, years, ai, allQuestions: all, totalQuestions: all.length, totalLectures: lectures.length + years.length + ai.length};
  }).filter(s=>s.totalQuestions>0);
  return sortSubjects(filtered);
}

function setEmptyText(text, icon='📁'){ el('subjects-empty-text').textContent=text; const ic=el('subjects-empty').querySelector('.empty-icon'); if(ic) ic.textContent=icon; }
function renderSubjects(){ const container=el('subjects-list'); const empty=el('subjects-empty'); if(!container||!empty) return; state.displayedSubjects=getCurrentBrowseSubjects(); const searchTerm=String(el('subjects-search')?el('subjects-search').value:'').trim().toLowerCase(); const t=theme(); const pinnedSet=new Set(state.subjectPreferences.pinned||[]); const visible=state.displayedSubjects.filter(s=>s.name.toLowerCase().includes(searchTerm)); const titleMap={all:'Subjects', favorites:'Favorite Questions', wrong:'Wrong Questions'}; el('subjects-screen-title').textContent=titleMap[state.browseMode] || 'Subjects'; if(!state.displayedSubjects.length){ empty.classList.remove('hidden'); container.innerHTML=''; if(state.browseMode==='wrong') setEmptyText('لا توجد أسئلة خاطئة حتى الآن.','❌'); else if(state.browseMode==='favorites') setEmptyText('لا توجد أسئلة مفضلة حتى الآن.','⭐'); else setEmptyText('لم يتم العثور على مواد بعد. تأكد من أن مجلدات المواد موجودة في المستودع.','📁'); return; } empty.classList.add('hidden'); container.innerHTML=visible.map(subject=>{ const pinned=pinnedSet.has(subject.id); return `<div class="subject-card${state.openSubjectActionId===subject.id?' actions-open':''}" data-subject-id="${subject.id}" onclick="handleSubjectOpen('${subject.id}',event)" onmousedown="startSubjectLongPress('${subject.id}')" ontouchstart="startSubjectLongPress('${subject.id}')" onmouseup="cancelSubjectLongPress()" onmouseleave="cancelSubjectLongPress()" ontouchend="cancelSubjectLongPress()" ontouchcancel="cancelSubjectLongPress()">${pinned?'<span class="subject-pin-badge">📌 مثبت</span>':''}<div class="subject-card-top"><div class="subject-icon-box">${t.icons.subject}</div><div class="subject-title-wrap"><div class="subject-badge-text">${escapeHtml(subject.name)}</div><div class="subject-subtitle">اضغط مطولاً للترتيب والتثبيت</div></div></div><div class="subject-meta"><div><span>${t.icons.lectures} الأقسام/الملفات</span><strong>${subject.totalLectures}</strong></div><div><span>${t.icons.progress} Questions</span><strong>${subject.totalQuestions}</strong></div><div><span>${t.icons.years} Years</span><strong>${subject.years.length}</strong></div></div>${state.browseMode==='all'?`<div class="subject-actions" onclick="event.stopPropagation()"><button class="subject-action-btn" onclick="moveSubject('${subject.id}','up')">⬆️ أعلى</button><button class="subject-action-btn" onclick="moveSubject('${subject.id}','down')">⬇️ أسفل</button><button class="subject-action-btn" onclick="togglePinSubject('${subject.id}')">${pinned?'📍 إلغاء التثبيت':'📌 تثبيت بالأعلى'}</button></div>`:''}</div>`; }).join(''); if(!visible.length) container.innerHTML='<div class="empty-state"><div class="empty-icon">🔎</div><p>لا توجد مواد مطابقة للبحث.</p></div>'; }
function filterSubjects(){ renderSubjects(); }
function openExams(){ state.browseMode='all'; renderSubjects(); showScreen('subjects-screen'); }
function openSection(section){ if(section==='wrong'){ state.browseMode='wrong'; renderSubjects(); showScreen('subjects-screen'); } else if(section==='favorites'){ state.browseMode='favorites'; renderSubjects(); showScreen('subjects-screen'); } else if(section==='search'){ showScreen('search-screen'); el('search-input').value=''; el('search-results').innerHTML=''; } else openExams(); }
function backToSubjects(){ renderSubjects(); showScreen('subjects-screen'); }
function moveSubject(subjectId,direction){ normalizeSubjectPreferences(); const arr=state.subjectPreferences.order.slice(); const idx=arr.indexOf(subjectId); if(idx===-1) return; const target=direction==='up'?idx-1:idx+1; if(target<0||target>=arr.length) return; [arr[idx],arr[target]]=[arr[target],arr[idx]]; state.subjectPreferences.order=arr; saveSubjectPreferences(); state.subjects=sortSubjects(state.subjects); renderSubjects(); openSubjectActions(subjectId); updateStatisticsIfOpen(); renderMemories(); }
function togglePinSubject(subjectId){ normalizeSubjectPreferences(); const pinned=new Set(state.subjectPreferences.pinned||[]); if(pinned.has(subjectId)) pinned.delete(subjectId); else pinned.add(subjectId); state.subjectPreferences.pinned=Array.from(pinned); saveSubjectPreferences(); state.subjects=sortSubjects(state.subjects); renderSubjects(); openSubjectActions(subjectId); updateStatisticsIfOpen(); renderMemories(); }
function openSubjectActions(subjectId){ state.openSubjectActionId=subjectId; document.querySelectorAll('.subject-card').forEach(card=>card.classList.toggle('actions-open', card.getAttribute('data-subject-id')===subjectId)); }
function closeSubjectActions(){ state.openSubjectActionId=null; document.querySelectorAll('.subject-card').forEach(card=>card.classList.remove('actions-open')); }
function startSubjectLongPress(subjectId){ if(state.browseMode!=='all') return; clearTimeout(state.longPressTimer); state.longPressTimer=setTimeout(()=>openSubjectActions(subjectId),420); }
function cancelSubjectLongPress(){ clearTimeout(state.longPressTimer); state.longPressTimer=null; }
function handleSubjectOpen(subjectId,event){ if(event && event.target && event.target.closest('.subject-action-btn')) return; if(state.openSubjectActionId===subjectId) return; openSubject(subjectId); }

function openSubject(subjectId){ state.currentSubject=state.displayedSubjects.find(s=>s.id===subjectId) || state.subjects.find(s=>s.id===subjectId) || null; if(!state.currentSubject){ showToast('المادة غير موجودة.','error'); return; } const t=theme(); el('subject-sections-title').textContent=state.currentSubject.name; el('subject-sections-summary').innerHTML=`<div class="subject-summary-grid"><div><span>${t.icons.lectures} المحاضرات</span><strong>${state.currentSubject.lectures.length}</strong></div><div><span>${t.icons.years} Years</span><strong>${state.currentSubject.years.length}</strong></div><div><span>${t.icons.ai} AI</span><strong>${state.currentSubject.ai.length}</strong></div><div><span>${t.icons.progress} إجمالي الأسئلة</span><strong>${state.currentSubject.totalQuestions}</strong></div></div>`; const cards=[]; if(state.currentSubject.lectures.length) cards.push(buildCategoryCard('lectures','Lectures','Lectures',state.currentSubject.lectures.length,countQuestions(state.currentSubject.lectures),true)); if(state.currentSubject.years.length) cards.push(buildCategoryCard('years','Years','Years',state.currentSubject.years.length,countQuestions(state.currentSubject.years),true)); if(state.currentSubject.ai.length || (state.browseMode==='all' && state.currentSubject.hasAiFolder)) cards.push(buildCategoryCard('ai','AI','AI',state.currentSubject.ai.length,countQuestions(state.currentSubject.ai),state.currentSubject.ai.length>0 || (state.browseMode==='all' && state.currentSubject.hasAiFolder))); el('subject-categories').innerHTML=cards.join('') || '<div class="empty-state"><div class="empty-icon">📭</div><p>لا توجد ملفات TXT بعد داخل هذه المادة.</p></div>'; showScreen('subject-sections-screen'); }
function countQuestions(groups){ return groups.reduce((sum,g)=>sum+g.questions.length,0); }
function buildCategoryCard(type,title,badgeText,itemCount,totalQuestions,enabled){ if(!enabled) return ''; return `<button class="category-card" onclick="openSubjectCategory('${type}')"><span class="category-badge">${badgeText}</span><div class="category-meta"><div><span>المحاضرات</span><strong>${itemCount}</strong></div><div><span>الأسئلة</span><strong>${totalQuestions}</strong></div></div></button>`; }
function openSubjectCategory(type){ if(!state.currentSubject) return; let groups=[], title=''; let placeholder='ابحث...'; if(type==='lectures'){ groups=state.currentSubject.lectures; title='Lectures'; placeholder='ابحث عن اسم المحاضرة...'; } else if(type==='years'){ groups=state.currentSubject.years; title='Years'; placeholder='ابحث عن الدفعة...'; } else { groups=state.currentSubject.ai; title='AI'; placeholder='ابحث عن ملف AI...'; } showSelectionScreen(groups, title, { backContext:'subject', searchable:true, searchPlaceholder:placeholder, sectionType:type, collectionType: state.browseMode!=='all' ? state.browseMode : null, displayLabel: state.currentSubject.name + ' · ' + title }); }
function backFromSelection(){ if(state.currentSelectionMeta && state.currentSelectionMeta.backContext==='subject' && state.currentSubject) openSubject(state.currentSubject.id); else goHome(); }

function showSelectionScreen(groups,title,meta){ state.selectedGroups=[]; state.currentGroups=groups.slice(); state.selectedMode=null; state.selectedDirection=null; state.extraTime=0; state.extraTimeAdded=false; state.currentSelectionMeta=meta||{}; showScreen('selection-screen'); el('selection-title').textContent=title; const searchContainer=el('selection-search-container'); const searchInput=el('selection-search'); if(meta&&meta.searchable){ searchContainer.classList.remove('hidden'); searchInput.value=''; searchInput.placeholder=meta.searchPlaceholder||'ابحث...'; } else { searchContainer.classList.add('hidden'); searchInput.value=''; } const list=el('selection-list'); const t=theme(); list.innerHTML=''; groups.forEach((group,idx)=>{ const icon=group.type==='ai'?t.icons.ai:(group.type==='year'?t.icons.years:t.icons.lectures); const item=document.createElement('div'); item.className='selection-item'; item.setAttribute('data-group-name',(group.name+' '+(group.subjectName||'')).toLowerCase()); item.innerHTML=`<input type="checkbox" id="group-${idx}" onchange="toggleGroupSelection(${idx})"><label for="group-${idx}" style="width:100%; cursor:pointer;"><strong>${icon} ${escapeHtml(group.name)}</strong><br><small style="color:var(--text-muted)">${group.questions.length} questions</small></label>`; item.addEventListener('click',function(event){ if(event.target.closest('input')||event.target.closest('label')) return; const cb=item.querySelector('input'); cb.checked=!cb.checked; toggleGroupSelection(idx); }); list.appendChild(item); }); el('selection-footer').classList.add('hidden'); el('direction-selection').classList.add('hidden'); el('timer-options').classList.add('hidden'); el('start-section').classList.add('hidden'); document.querySelectorAll('.btn-mode').forEach(btn=>btn.classList.remove('active')); document.querySelectorAll('.btn-direction').forEach(btn=>btn.classList.remove('active')); }
function filterSelectionList(){ const term=String(el('selection-search').value||'').toLowerCase().trim(); document.querySelectorAll('#selection-list .selection-item').forEach(item=>{ const name=item.getAttribute('data-group-name')||''; item.style.display=name.includes(term)?'':'none'; }); }
function toggleGroupSelection(idx){ const existing=state.selectedGroups.indexOf(idx); if(existing>-1) state.selectedGroups.splice(existing,1); else state.selectedGroups.push(idx); document.querySelectorAll('#selection-list .selection-item').forEach((item,itemIdx)=>item.classList.toggle('selected', state.selectedGroups.includes(itemIdx))); updateSelectionFooter(); }
function updateSelectionFooter(){ const footer=el('selection-footer'); const totalQuestions=state.selectedGroups.reduce((sum,idx)=>sum+state.currentGroups[idx].questions.length,0); if(state.selectedGroups.length>0){ footer.classList.remove('hidden'); el('selected-count').textContent=totalQuestions+' questions selected'; const input=el('question-count-input'); input.max=totalQuestions; input.value=totalQuestions; el('max-questions-label').textContent='/ '+totalQuestions; } else footer.classList.add('hidden'); state.selectedMode=null; state.selectedDirection=null; el('direction-selection').classList.add('hidden'); el('timer-options').classList.add('hidden'); el('start-section').classList.add('hidden'); document.querySelectorAll('.btn-mode').forEach(btn=>btn.classList.remove('active')); document.querySelectorAll('.btn-direction').forEach(btn=>btn.classList.remove('active')); }
function selectMode(mode){ state.selectedMode=mode; state.selectedDirection=null; state.extraTime=0; state.extraTimeAdded=false; document.querySelectorAll('.btn-mode').forEach(btn=>btn.classList.remove('active')); el(mode==='training'?'btn-training-mode':'btn-exam-mode').classList.add('active'); document.querySelectorAll('.btn-direction').forEach(btn=>btn.classList.remove('active')); el('direction-selection').classList.remove('hidden'); el('timer-options').classList.add('hidden'); el('start-section').classList.add('hidden'); }
function selectDirection(direction){ state.selectedDirection=direction; document.querySelectorAll('.btn-direction').forEach(btn=>btn.classList.remove('active')); el(direction==='oneway'?'btn-oneway':'btn-twoway').classList.add('active'); if(state.selectedMode==='exam'){ const count=parseInt(el('question-count-input').value,10)||0; el('base-time-display').textContent=count+' min'; el('extra-time-display').textContent='+0 min'; el('total-time-display').textContent=count+' min'; el('timer-options').classList.remove('hidden'); const btn=el('btn-add-extra'); btn.disabled=false; btn.textContent='+ إضافة 5 دقائق'; btn.classList.remove('active'); state.extraTime=0; state.extraTimeAdded=false; } else el('timer-options').classList.add('hidden'); el('start-section').classList.remove('hidden'); }
function addExtraTime(){ const count=parseInt(el('question-count-input').value,10)||0; const btn=el('btn-add-extra'); if(!state.extraTimeAdded){ state.extraTime=5; state.extraTimeAdded=true; el('extra-time-display').textContent='+5 min'; el('total-time-display').textContent=(count+5)+' min'; btn.disabled=false; btn.textContent='− إزالة 5 دقائق'; btn.classList.add('active'); } else { state.extraTime=0; state.extraTimeAdded=false; el('extra-time-display').textContent='+0 min'; el('total-time-display').textContent=count+' min'; btn.disabled=false; btn.textContent='+ إضافة 5 دقائق'; btn.classList.remove('active'); } }
function confirmStartExam(){ try{ if(!state.selectedMode || !state.selectedDirection){ showToast('يرجى اختيار النمط واتجاه التنقل.','error'); return; } const count=parseInt(el('question-count-input').value,10); if(!count || count<1){ showToast('يرجى إدخال عدد صحيح من الأسئلة.','error'); return; } let questions=[]; state.selectedGroups.forEach(idx=>{ if(state.currentGroups[idx] && Array.isArray(state.currentGroups[idx].questions)) questions=questions.concat(state.currentGroups[idx].questions); }); if(!questions.length){ showToast('لا توجد أسئلة متاحة للبدء.','error'); return; } const selectedGroupObjects=state.selectedGroups.map(idx=>state.currentGroups[idx]).filter(Boolean); const historySubjectName=selectedGroupObjects[0]?.subjectName || state.currentSubject?.name || 'Unknown Subject'; const historyGroups=selectedGroupObjects.map(g=>({ name:g.name, type:g.type || state.currentSelectionMeta?.sectionType || 'lecture' })); questions=shuffleArray(questions).slice(0, count); startExamSession(questions, state.selectedMode, state.selectedDirection, state.currentSelectionMeta ? state.currentSelectionMeta.sectionType : 'custom', state.extraTime, { collectionType: state.currentSelectionMeta ? state.currentSelectionMeta.collectionType : null, displayLabel: state.currentSelectionMeta ? state.currentSelectionMeta.displayLabel : 'Exam', historySubjectName, historyGroups }); }catch(err){ console.error('confirmStartExam error', err); showToast('حدث خطأ عند بدء الامتحان. افتح Console إن استمرت المشكلة.','error'); } }

function startExamSession(questions,mode,direction,sourceLabel,extraMinutes,meta){ state.currentExam={ mode, direction, sourceLabel:sourceLabel||'custom', collectionType: meta && meta.collectionType ? meta.collectionType : null, displayLabel: meta && meta.displayLabel ? meta.displayLabel : (sourceLabel||'Exam'), historySubjectName: meta?.historySubjectName || null, historyGroups: meta?.historyGroups || [], questions:questions.map(q=>Object.assign({},q)), currentIndex:0, answers:new Array(questions.length).fill(null), firstAnswers:new Array(questions.length).fill(null), startTime:Date.now(), totalTime:(questions.length+(extraMinutes||0))*60*1000, submitted:false, showAnswer:false, masteredWrongIds:[] }; saveExamState(); showScreen('exam-screen'); renderExam(); if(mode==='exam') startTimer(); scrollQuestionIntoView(false); }
function renderRemoveWrongBtn(){ if(!state.currentExam || state.currentExam.collectionType!=='wrong' || state.currentExam.mode!=='training') return ''; const idx=state.currentExam.currentIndex; const q=state.currentExam.questions[idx]; const answered=state.currentExam.firstAnswers[idx]; if(answered===null || !isAnswerCorrect(q, answered) || !state.wrongQuestions.includes(q.id)) return ''; return `<button class="btn-secondary mt-20" onclick="confirmRemoveCurrentWrong()">✅ إزالة السؤال من الأخطاء</button>`; }
function startSpecialExam(questions, mode, direction){ startExamSession(shuffleArray(questions.slice()), mode, direction||'twoway', 'special', 5, { collectionType:null, displayLabel:'Special Exam', historySubjectName:'Special Exam', historyGroups:[] }); }

function renderExam(){ if(!state.currentExam) return; const t=theme(); const questions=state.currentExam.questions; const idx=state.currentExam.currentIndex; const q=questions[idx]; if(!q) return; let progressText=t.icons.progress+' '+(idx+1)+'/'+questions.length; if(state.currentExam.mode==='training'){ const answered=state.currentExam.firstAnswers.filter(x=>x!==null).length; const correct=state.currentExam.firstAnswers.filter((ans,i)=>ans!==null && isAnswerCorrect(questions[i],ans)).length; const pct=answered>0 ? Math.round((correct/answered)*100) : 0; progressText+=' · '+t.icons.success+correct+' · '+pct+'%'; } else progressText+=' · '+(questions.length-idx)+' left'; el('exam-progress').textContent=progressText; renderGrid(); const correctIdx=getCorrectIndex(q); const showAnswerState=state.currentExam.mode==='training' && state.currentExam.showAnswer; const fav=state.favorites.includes(q.id); el('question-container').innerHTML=`<div class="question-header"><span class="question-number">Q${escapeHtml(q.number||String(idx+1))}</span><div class="question-actions"><button class="icon-btn ${fav?'active':''}" onclick="toggleFavorite('${q.id}')">💚</button><button class="icon-btn" onclick="toggleQuestionLocation()">${t.icons.location}</button></div></div><p class="question-text">${escapeHtml(q.text)}</p><div class="options-list">${q.options.map((opt,i)=>{ let cls='option-btn'; if(state.currentExam.answers[idx]===i) cls+=' selected'; if(showAnswerState){ if(i===correctIdx) cls+=' correct'; else if(state.currentExam.answers[idx]===i && i!==correctIdx) cls+=' wrong'; } return '<button class="'+cls+'" onclick="selectOption('+i+')">'+escapeHtml(opt)+'</button>'; }).join('')}</div><div class="explanation-box ${showAnswerState?'visible':''}"><strong>Explanation:</strong> ${escapeHtml(q.explanation||'No explanation available.')}</div>${renderRemoveWrongBtn()}`; renderExamNav(); }
function renderGrid(){ if(!state.currentExam) return; const grid=el('question-grid'); grid.innerHTML=''; state.currentExam.questions.forEach((q,idx)=>{ let cls='grid-btn'; if(idx===state.currentExam.currentIndex) cls+=' current'; else if(state.currentExam.answers[idx]!==null){ if(state.currentExam.mode==='training' && state.currentExam.firstAnswers[idx]!==null) cls+=isAnswerCorrect(q,state.currentExam.firstAnswers[idx])?' answered':' wrong'; else cls+=' answered'; } if(state.currentExam.direction==='oneway' && idx<state.currentExam.currentIndex) cls+=' disabled'; const btn=document.createElement('button'); btn.className=cls; btn.textContent=String(idx+1); btn.onclick=()=>navigateToQuestion(idx); grid.appendChild(btn); }); }
function renderExamNav(){ if(!state.currentExam) return; const nav=el('exam-nav'); const idx=state.currentExam.currentIndex, last=state.currentExam.questions.length-1; let prevBtn='<span></span>', nextBtn='<span></span>'; if(state.currentExam.direction==='twoway' && idx>0) prevBtn='<button class="btn-secondary" onclick="prevQuestion()">Previous ←</button>'; if(state.currentExam.mode==='training'){ if(state.currentExam.showAnswer) nextBtn=idx<last?'<button class="btn-primary" onclick="nextQuestion()">Next →</button>':'<button class="btn-primary" onclick="finishExam()">Finish</button>'; else if(state.currentExam.answers[idx]!==null) nextBtn='<button class="btn-small" onclick="showAnswer()">Show Answer</button>'; } else if(state.currentExam.answers[idx]!==null) nextBtn=idx<last?'<button class="btn-primary" onclick="nextQuestion()">Next →</button>':'<button class="btn-primary" onclick="finishExam()">Finish</button>'; nav.innerHTML=prevBtn + nextBtn; }
function selectOption(optionIndex){ if(!state.currentExam || state.currentExam.submitted) return; if(state.currentExam.mode==='training' && state.currentExam.showAnswer) return; const idx=state.currentExam.currentIndex; const q=state.currentExam.questions[idx]; state.currentExam.answers[idx]=optionIndex; if(state.currentExam.firstAnswers[idx]===null) state.currentExam.firstAnswers[idx]=optionIndex; const correct=isAnswerCorrect(q,optionIndex); if(state.currentExam.mode==='training'){ if(state.settings.feedbackEnabled) playEffectSound(correct?'right':'wrong'); if(correct){ state.currentExam.showAnswer=true; if(state.settings.animations!==false) showFireworks(48,12); } else { if(!state.wrongQuestions.includes(q.id)){ state.wrongQuestions.push(q.id); saveWrongQuestions(); } showToast(themeWrongMessage(),'error'); } saveExamState(); renderExam(); } else { saveExamState(); renderExam(); } }
function themeWrongMessage(){ switch(state.settings.theme){ case 'desert': return 'الجواب انحرف عن مسار القافلة.'; case 'space': return 'Trajectory mismatch. Try again.'; case 'pirates': return 'Wrong turn on the treasure map.'; case 'castle': return 'The dragon dodged that answer.'; case 'lab': return 'Experiment unstable. Re-check the sample.'; default: return 'إجابة خاطئة.'; } }
function showAnswer(){ if(!state.currentExam) return; state.currentExam.showAnswer=true; const idx=state.currentExam.currentIndex; const q=state.currentExam.questions[idx]; const ans=state.currentExam.firstAnswers[idx]; if(ans!==null && !isAnswerCorrect(q,ans) && !state.wrongQuestions.includes(q.id)){ state.wrongQuestions.push(q.id); saveWrongQuestions(); } saveExamState(); renderExam(); }
function nextQuestion(){ if(!state.currentExam) return; if(state.currentExam.currentIndex<state.currentExam.questions.length-1){ state.currentExam.currentIndex+=1; state.currentExam.showAnswer=false; saveExamState(); renderExam(); scrollQuestionIntoView(true); } }
function prevQuestion(){ if(!state.currentExam || state.currentExam.direction!=='twoway') return; if(state.currentExam.currentIndex>0){ state.currentExam.currentIndex-=1; if(state.currentExam.mode==='training') state.currentExam.showAnswer=state.currentExam.answers[state.currentExam.currentIndex]!==null; saveExamState(); renderExam(); scrollQuestionIntoView(true); } }
function navigateToQuestion(index){ if(!state.currentExam) return; if(state.currentExam.direction==='oneway' && index!==state.currentExam.currentIndex) return; state.currentExam.currentIndex=index; if(state.currentExam.mode==='training') state.currentExam.showAnswer=state.currentExam.answers[index]!==null; saveExamState(); renderExam(); scrollQuestionIntoView(true); }
function scrollQuestionIntoView(smooth){ const q=el('question-container'); if(!q) return; const top=q.getBoundingClientRect().top + window.scrollY - 12; window.scrollTo({top, behavior:smooth && state.settings.animations!==false ? 'smooth':'auto'}); }
function toggleQuestionLocation(){ if(!state.currentExam) return; const q=state.currentExam.questions[state.currentExam.currentIndex]; const parts=[]; if(q.subjectName) parts.push('المادة: '+q.subjectName); if(q.lectureName) parts.push('الملف: '+q.lectureName); if(q.batchName) parts.push('الدفعة: '+q.batchName); if(q.pageNumber) parts.push('الصفحة: '+q.pageNumber); showToast(parts.join(' | ') || 'لا توجد بيانات موقع متاحة.','info',3000); }
function confirmRemoveCurrentWrong(){ if(!state.currentExam || state.currentExam.collectionType!=='wrong') return; const q=state.currentExam.questions[state.currentExam.currentIndex]; askConfirm('هل أتقنت هذا السؤال وتريد إزالته من الأسئلة الخاطئة؟', ()=>removeWrongQuestionsByIds([q.id])); }
function removeWrongQuestionsByIds(ids){ const set=new Set(ids); state.wrongQuestions = state.wrongQuestions.filter(id=>!set.has(id)); saveWrongQuestions(); updateStatisticsIfOpen(); if(state.currentExam){ state.currentExam.masteredWrongIds = state.currentExam.masteredWrongIds.filter(id=>!set.has(id)); renderExam(); } if(state.browseMode==='wrong') renderSubjects(); showToast('تمت إزالة السؤال/الأسئلة من قائمة الأخطاء.','success'); }
function toggleGrid(){ const grid=el('question-grid'); const btn=el('btn-grid-toggle'); grid.classList.toggle('hidden'); btn.innerHTML=grid.classList.contains('hidden')?'<span>☰</span> إظهار الشبكة':'<span>☰</span> إخفاء الشبكة'; }
function exitExam(){ if(state.currentExam && !state.currentExam.submitted) askConfirm('هل تريد الخروج؟ سيتم حفظ التقدم الحالي.', ()=>{ saveExamState(); state.currentExam=null; clearInterval(state.timerInterval); state.timerInterval=null; goHome(); }); else { state.currentExam=null; goHome(); } }

function startTimer(){ clearInterval(state.timerInterval); const timerEl=el('exam-timer'); timerEl.classList.remove('hidden'); state.timerInterval=setInterval(()=>{ if(!state.currentExam || state.currentExam.submitted){ clearInterval(state.timerInterval); state.timerInterval=null; return; } const elapsed=Date.now()-state.currentExam.startTime; const remaining=state.currentExam.totalTime-elapsed; if(remaining<=0){ clearInterval(state.timerInterval); state.timerInterval=null; timeUp(); return; } const mins=Math.floor(remaining/60000); const secs=Math.floor((remaining%60000)/1000); timerEl.textContent=mins+':'+String(secs).padStart(2,'0'); timerEl.classList.toggle('timer-danger', remaining<=60000); },1000); }
function timeUp(){ if(!state.currentExam) return; const unanswered=state.currentExam.answers.filter(a=>a===null).length; showToast('انتهى الوقت! يوجد '+unanswered+' سؤالًا بدون إجابة.','error'); finishExam(); }
function recordExamMemory(){ if(!state.currentExam) return; const end = state.currentExam.endTime || Date.now(); const start = state.currentExam.startTime || end; const answers = state.currentExam.mode==='exam' ? state.currentExam.answers : state.currentExam.firstAnswers; state.currentExam.questions.forEach((q,idx)=>{ if(answers[idx]===null) return; if(!state.questionsFirstSeen[q.id]) state.questionsFirstSeen[q.id] = { ts:end, subjectName:q.subjectName || 'Unknown' }; }); const stats = calculateScore(state.currentExam); const mastered = [];
  if(state.currentExam.collectionType==='wrong'){
    state.currentExam.questions.forEach((q,idx)=>{ const ans=answers[idx]; if(ans!==null && isAnswerCorrect(q,ans) && state.wrongQuestions.includes(q.id)) mastered.push(q.id); });
    state.currentExam.masteredWrongIds = Array.from(new Set(mastered));
  }
  state.examHistory.push({ id:'exam_'+Date.now()+'_'+Math.random().toString(36).slice(2,7), startedAt:start, endedAt:end, durationMs:end-start, mode:state.currentExam.mode, sourceLabel:state.currentExam.displayLabel || state.currentExam.sourceLabel || 'Exam', collectionType:state.currentExam.collectionType || null, total:stats.total, correct:stats.correct, score:stats.score, subjectName: state.currentExam.historySubjectName || (state.currentExam.questions[0]?.subjectName || 'Unknown Subject'), groups: state.currentExam.historyGroups || [] });
  saveMemoryStores();
}
function finishExam(){ if(!state.currentExam) return; state.currentExam.submitted=true; state.currentExam.endTime=Date.now(); if(state.currentExam.mode==='exam'){ state.currentExam.questions.forEach((q,idx)=>{ const ans=state.currentExam.answers[idx]; if(ans!==null && !isAnswerCorrect(q,ans) && !state.wrongQuestions.includes(q.id)) state.wrongQuestions.push(q.id); }); saveWrongQuestions(); } clearInterval(state.timerInterval); state.timerInterval=null; saveProgress(); recordExamMemory(); clearExamState(); if(state.currentExam.mode==='exam'){ showScreen('results-screen'); showWaitingMessages(); } else showResults(); }
function saveProgress(){ if(!state.currentExam) return; const answers=state.currentExam.mode==='exam'?state.currentExam.answers:state.currentExam.firstAnswers; state.currentExam.questions.forEach((q,idx)=>{ if(answers[idx]===null) return; addProgressId('subject:'+q.subjectName,q.id); const actual=q.originalSourceType||q.sourceType; if(actual==='lecture') addProgressId('lecture:'+q.subjectName+'/'+q.lectureName,q.id); if(actual==='ai') addProgressId('ai:'+q.subjectName+'/'+q.lectureName,q.id); if(q.batchName) addProgressId('year:'+q.subjectName+'/'+q.batchName,q.id); }); saveProgressStore(); updateStatisticsIfOpen(); renderMemories(); }
function showWaitingMessages(){ const wai
